/*CSD Queries */

/* CLASS */
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE)
  values (1, 1, 1, null, 'ORIGINAL FINISH REGULAR RUN DIVISION', NOW());

insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE)
  values (8, 1, 1, null, 'ORIGINAL FINISH SPECIAL RUN DIVISION', NOW());

insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE)
  values (15, 1, 1, null, 'COLLECTIBILITY DIVISION20.CUSTOMIZED DIVISION', NOW());

insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE)
  values (29, 1, 1, null, 'FOAL DIVISION35.MINI DIVISION', NOW());

insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE)
  values (39, 1, 1, null, 'NOVICE PERFORMANCE SECTION', NOW());

insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE)
  values (40, 1, 1, null, 'OPEN O.F. PERFORMANCE DIVISION', NOW());

insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE)
  values (44, 1, 1, null, 'OPEN CM PERFORMANCE DIVISION', NOW());


/* SECTION */
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE)
  values (2, 1, 1, 1, 'Draft Breed & Type Section', NOW());

insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE)
  values (3, 1, 1, 1, 'Pony Breed & Type Section', NOW());

insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE)
  values (4, 1, 1, 1, 'Stock Breed & Type Section', NOW());

insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE)
  values (5, 1, 1, 1, 'Light & Gaited Breed  & Type Section', NOW());

insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE)
  values (6, 1, 1, 1, 'Sport Breed & Type Section', NOW());

insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE)
  values (7, 1, 1, 1, 'Spanish, North American & Other Breed & Type Section', NOW());







