SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema frithi_HORSESHOW
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `frithi_HORSESHOW` ;
CREATE SCHEMA IF NOT EXISTS `frithi_HORSESHOW` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci ;
-- -----------------------------------------------------
-- Schema frithi_HORSESHOW_WEBSITE
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `frithi_HORSESHOW_WEBSITE` ;
CREATE SCHEMA IF NOT EXISTS `frithi_HORSESHOW_WEBSITE` DEFAULT CHARACTER SET latin1 ;
USE `frithi_HORSESHOW` ;

-- -----------------------------------------------------
-- Table `frithi_HORSESHOW`.`USER_ROLE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frithi_HORSESHOW`.`USER_ROLE` ;

CREATE TABLE IF NOT EXISTS `frithi_HORSESHOW`.`USER_ROLE` (
  `ID` INT NOT NULL,
  `NAME` VARCHAR(45) NOT NULL,
  `DESCRIPTION` VARCHAR(45) NOT NULL,
  `ADD_DATE` DATETIME NOT NULL,
  `INACTIVE_DATE` DATETIME NULL,
  `TIMESTAMP` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frithi_HORSESHOW`.`USER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frithi_HORSESHOW`.`USER` ;

CREATE TABLE IF NOT EXISTS `frithi_HORSESHOW`.`USER` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `LOGIN_USERNAME` VARCHAR(45) NOT NULL,
  `LOGIN_PASSWORD` VARCHAR(60) NOT NULL,
  `EMAIL_PRI` VARCHAR(45) NOT NULL,
  `EMAIL_ALT` VARCHAR(45) NULL,
  `ADD_DATE` DATETIME NOT NULL,
  `LAST_LOGIN_DATE` DATETIME NULL,
  `INACTIVIE_DATE` DATETIME NULL,
  `LOGIN_COUNT` INT NOT NULL,
  `LOGIN_FAILED_ATTEMPTS` INT NOT NULL,
  `COMMENT` VARCHAR(100) NULL,
  `ACTIVATION_KEY` VARCHAR(100) NULL,
  `USER_ROLE_ID` INT NOT NULL,
  `TIMESTAMP` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`, `USER_ROLE_ID`),
  UNIQUE INDEX `webUserID_UNIQUE` (`ID` ASC),
  UNIQUE INDEX `webUserLoginName_UNIQUE` (`LOGIN_USERNAME` ASC),
  INDEX `fk_USER_USER_ROLE1_idx` (`USER_ROLE_ID` ASC),
  UNIQUE INDEX `ACTIVATION_KEY_UNIQUE` (`ACTIVATION_KEY` ASC),
  CONSTRAINT `fk_USER_USER_ROLE1`
    FOREIGN KEY (`USER_ROLE_ID`)
    REFERENCES `frithi_HORSESHOW`.`USER_ROLE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frithi_HORSESHOW`.`DOCUMENT_TYPE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frithi_HORSESHOW`.`DOCUMENT_TYPE` ;

CREATE TABLE IF NOT EXISTS `frithi_HORSESHOW`.`DOCUMENT_TYPE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NOT NULL,
  `DESCRIPTION` VARCHAR(100) NULL,
  `EXTENSION` CHAR(5) NOT NULL,
  `ADD_DATE` DATETIME NOT NULL,
  `TIMESTAMP` TIMESTAMP NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `documentTypeID_UNIQUE` (`ID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frithi_HORSESHOW`.`FILE_LOAD_STATUS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frithi_HORSESHOW`.`FILE_LOAD_STATUS` ;

CREATE TABLE IF NOT EXISTS `frithi_HORSESHOW`.`FILE_LOAD_STATUS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NOT NULL,
  `DESCRIPTION` VARCHAR(100) NULL,
  `ADD_DATE` VARCHAR(45) NOT NULL,
  `TIMESTAMP` TIMESTAMP NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frithi_HORSESHOW`.`DOCUMENT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frithi_HORSESHOW`.`DOCUMENT` ;

CREATE TABLE IF NOT EXISTS `frithi_HORSESHOW`.`DOCUMENT` (
  `ID` INT NOT NULL,
  `DOCUMENT_TYPE_ID` INT NOT NULL,
  `FILE_LOAD_STATUS_ID` INT NOT NULL,
  `FILE_LOCATION` VARCHAR(45) NULL,
  `FILE_SIZE` VARCHAR(45) NULL,
  `DESCRIPTION` VARCHAR(45) NULL,
  `ADD_DATE` DATETIME NOT NULL,
  `TIMESTAMP` TIMESTAMP NOT NULL,
  PRIMARY KEY (`ID`, `DOCUMENT_TYPE_ID`),
  UNIQUE INDEX `documentID_UNIQUE` (`ID` ASC),
  INDEX `fk_DOCUMENT_DOCUMENT_TYPE1_idx` (`DOCUMENT_TYPE_ID` ASC),
  INDEX `fk_DOCUMENT_FILE_LOAD_STATUS1_idx` (`FILE_LOAD_STATUS_ID` ASC),
  CONSTRAINT `fk_DOCUMENT_DOCUMENT_TYPE1`
    FOREIGN KEY (`DOCUMENT_TYPE_ID`)
    REFERENCES `frithi_HORSESHOW`.`DOCUMENT_TYPE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DOCUMENT_FILE_LOAD_STATUS1`
    FOREIGN KEY (`FILE_LOAD_STATUS_ID`)
    REFERENCES `frithi_HORSESHOW`.`FILE_LOAD_STATUS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frithi_HORSESHOW`.`PERSON`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frithi_HORSESHOW`.`PERSON` ;

CREATE TABLE IF NOT EXISTS `frithi_HORSESHOW`.`PERSON` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `PERSON_KEY` VARCHAR(76) NULL,
  `SHOW_EXHIBITOR_ID` VARCHAR(45) NULL,
  `FIRST_NAME` VARCHAR(60) NOT NULL,
  `LAST_NAME` VARCHAR(60) NOT NULL,
  `MIDDLE_NAME` VARCHAR(60) NULL,
  `SUFFIX` VARCHAR(60) NULL,
  `NICKNAME` VARCHAR(60) NULL,
  `ADDRESS_LINE_1` VARCHAR(75) NULL,
  `ADDRESS_LINE_2` VARCHAR(75) NULL,
  `ADDRESS_LINE_3` VARCHAR(75) NULL,
  `CITY` VARCHAR(45) NULL,
  `STATE` CHAR(2) NULL,
  `ZIP` VARCHAR(20) NULL,
  `EMAIL` VARCHAR(75) NULL,
  `PHONE_NBR_HOME` CHAR(10) NULL,
  `PHONE_NBR_CELL` CHAR(10) NULL,
  `PHONE_NBR_ALT` CHAR(10) NULL,
  `ADD_DATE` DATETIME NOT NULL,
  `INACTIVE_DATE` DATETIME NULL,
  `COMMENT` VARCHAR(100) NULL,
  `USER_ID` INT NULL,
  `DOCUMENT_ID` INT NULL,
  `TIMESTAMP` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `personID_UNIQUE` (`ID` ASC),
  UNIQUE INDEX `KEY_UNIQUE` (`PERSON_KEY` ASC),
  INDEX `fk_PERSON_USER1_idx` (`USER_ID` ASC),
  INDEX `fk_PERSON_DOCUMENT1_idx` (`DOCUMENT_ID` ASC),
  CONSTRAINT `fk_PERSON_USER1`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `frithi_HORSESHOW`.`USER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PERSON_DOCUMENT1`
    FOREIGN KEY (`DOCUMENT_ID`)
    REFERENCES `frithi_HORSESHOW`.`DOCUMENT` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frithi_HORSESHOW`.`BREED`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frithi_HORSESHOW`.`BREED` ;

CREATE TABLE IF NOT EXISTS `frithi_HORSESHOW`.`BREED` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `SHORT_NAME` VARCHAR(75) NULL,
  `LONG_NAME` VARCHAR(75) NOT NULL,
  `DESCRIPTION` VARCHAR(75) NULL,
  `ADD_DATE` DATETIME NOT NULL,
  `TIMESTAMP` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frithi_HORSESHOW`.`MODEL_TYPE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frithi_HORSESHOW`.`MODEL_TYPE` ;

CREATE TABLE IF NOT EXISTS `frithi_HORSESHOW`.`MODEL_TYPE` (
  `ID` INT NOT NULL,
  `NAME` VARCHAR(45) NULL,
  `DESCRIPTION` VARCHAR(45) NULL,
  `TIMESTAMP` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `modelTypeID_UNIQUE` (`ID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frithi_HORSESHOW`.`PERSON_MODEL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frithi_HORSESHOW`.`PERSON_MODEL` ;

CREATE TABLE IF NOT EXISTS `frithi_HORSESHOW`.`PERSON_MODEL` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `PERSON_ID` INT NOT NULL,
  `MODEL_TYPE_ID` INT NULL,
  `SHOW_MODEL_ID` VARCHAR(45) NOT NULL,
  `SHOW_MODEL_NAME` VARCHAR(45) NOT NULL,
  `SHOW_MODEL_BREED` VARCHAR(45) NULL,
  `SHOW_MODEL_GENDER` VARCHAR(45) NULL,
  `COMMENT` VARCHAR(100) NULL,
  `BREED_ID` INT NULL,
  `USER_FIELD_1` VARCHAR(45) NULL,
  `USER_FIELD_2` VARCHAR(45) NULL,
  `USER_FIELD_3` VARCHAR(45) NULL,
  `TIMESTAMP` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`, `PERSON_ID`),
  INDEX `fk_MODEL_PERSON1_idx` (`PERSON_ID` ASC),
  INDEX `fk_PERSON_MODEL_BREED1_idx` (`BREED_ID` ASC),
  INDEX `fk_PERSON_MODEL_MODEL_TYPE1_idx` (`MODEL_TYPE_ID` ASC),
  CONSTRAINT `fk_MODEL_PERSON1`
    FOREIGN KEY (`PERSON_ID`)
    REFERENCES `frithi_HORSESHOW`.`PERSON` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PERSON_MODEL_BREED1`
    FOREIGN KEY (`BREED_ID`)
    REFERENCES `frithi_HORSESHOW`.`BREED` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PERSON_MODEL_MODEL_TYPE1`
    FOREIGN KEY (`MODEL_TYPE_ID`)
    REFERENCES `frithi_HORSESHOW`.`MODEL_TYPE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frithi_HORSESHOW`.`HORSESHOW`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frithi_HORSESHOW`.`HORSESHOW` ;

CREATE TABLE IF NOT EXISTS `frithi_HORSESHOW`.`HORSESHOW` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME_ONE` VARCHAR(75) NOT NULL,
  `NAME_TWO` VARCHAR(75) NULL,
  `PRIVATE` CHAR NOT NULL DEFAULT 'Y',
  `ADDRESS_LINE_1` VARCHAR(75) NULL,
  `ADDRESS_LINE_2` VARCHAR(75) NULL,
  `ADDRESS_LINE_3` VARCHAR(75) NULL,
  `WEBSITE` VARCHAR(100) NULL,
  `EMAIL_PRIMARY` VARCHAR(75) NOT NULL,
  `EMAIL_SECONDARY` VARCHAR(75) NULL,
  `PHONE_NBR_PRIMARY` CHAR(10) NOT NULL,
  `PHONE_NBR_SECONDARY` CHAR(10) NULL,
  `DATE_ADD` VARCHAR(45) NOT NULL,
  `DATE_INACTIVE` VARCHAR(45) NULL,
  `RATING` VARCHAR(45) NULL,
  `NAHMSA_QUALIFY` CHAR NULL,
  `TIMESTAMP` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `horseShowID_UNIQUE` (`ID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frithi_HORSESHOW`.`DIVISION_TYPE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frithi_HORSESHOW`.`DIVISION_TYPE` ;

CREATE TABLE IF NOT EXISTS `frithi_HORSESHOW`.`DIVISION_TYPE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NOT NULL,
  `DESCRIPTION` VARCHAR(45) NULL,
  `ADD_DATE` DATETIME NOT NULL,
  `TIMESTAMP` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frithi_HORSESHOW`.`DIVISION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frithi_HORSESHOW`.`DIVISION` ;

CREATE TABLE IF NOT EXISTS `frithi_HORSESHOW`.`DIVISION` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `SHOW_ID` INT NOT NULL,
  `DIVISION_TYPE_ID` INT NOT NULL,
  `PRIMARY_DIVISION_ID` INT NULL,
  `NAME` VARCHAR(75) NOT NULL,
  `DESCRIPTION` VARCHAR(75) NULL,
  `ADD_DATE` DATETIME NOT NULL,
  `TIMESTAMP` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`, `SHOW_ID`, `DIVISION_TYPE_ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC),
  INDEX `fk_DIVISION_DIVISION_TYPE1_idx` (`DIVISION_TYPE_ID` ASC),
  CONSTRAINT `fk_DIVISION_DIVISION_TYPE1`
    FOREIGN KEY (`DIVISION_TYPE_ID`)
    REFERENCES `frithi_HORSESHOW`.`DIVISION_TYPE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frithi_HORSESHOW`.`RANK`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frithi_HORSESHOW`.`RANK` ;

CREATE TABLE IF NOT EXISTS `frithi_HORSESHOW`.`RANK` (
  `ID` INT NOT NULL,
  `SHORT_NAME` VARCHAR(45) NULL,
  `LONG_NAME` VARCHAR(45) NULL,
  `DESCRIPTION` VARCHAR(45) NULL,
  `DATE_ADD` DATETIME NOT NULL,
  `DATE_INACTIVE` DATETIME NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frithi_HORSESHOW`.`SHOW_STATUS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frithi_HORSESHOW`.`SHOW_STATUS` ;

CREATE TABLE IF NOT EXISTS `frithi_HORSESHOW`.`SHOW_STATUS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `SHORT_NAME` VARCHAR(45) NOT NULL,
  `LONG_NAME` VARCHAR(65) NOT NULL,
  `DESCRIPTION` VARCHAR(100) NULL,
  `COMMENT` VARCHAR(100) NULL,
  `ADD_DATE` DATETIME NOT NULL,
  `TIMESTAMP` TIMESTAMP NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frithi_HORSESHOW`.`SHOWS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frithi_HORSESHOW`.`SHOWS` ;

CREATE TABLE IF NOT EXISTS `frithi_HORSESHOW`.`SHOWS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `SHOW_STATUS_ID` INT NOT NULL,
  `HORSESHOW_ID` INT NOT NULL,
  `TITLE` VARCHAR(45) NOT NULL,
  `MAX_REGISTER` INT NOT NULL,
  `MAX_WAITING_LIST` INT NOT NULL,
  `ADD_DATE` DATETIME NOT NULL,
  `OPEN_DATE` DATETIME NOT NULL,
  `CLOSE_DATE` DATETIME NULL,
  `COMMENT` VARCHAR(100) NULL,
  PRIMARY KEY (`ID`, `SHOW_STATUS_ID`, `HORSESHOW_ID`),
  INDEX `fk_SHOW_SHOW_STATUS1_idx` (`SHOW_STATUS_ID` ASC),
  INDEX `fk_SHOW_HORSESHOW1_idx` (`HORSESHOW_ID` ASC),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC),
  CONSTRAINT `fk_SHOW_SHOW_STATUS1`
    FOREIGN KEY (`SHOW_STATUS_ID`)
    REFERENCES `frithi_HORSESHOW`.`SHOW_STATUS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SHOW_HORSESHOW1`
    FOREIGN KEY (`HORSESHOW_ID`)
    REFERENCES `frithi_HORSESHOW`.`HORSESHOW` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frithi_HORSESHOW`.`PLACEMENT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frithi_HORSESHOW`.`PLACEMENT` ;

CREATE TABLE IF NOT EXISTS `frithi_HORSESHOW`.`PLACEMENT` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DIVISION_ID` INT NOT NULL,
  `PERSON_MODEL_ID` INT NOT NULL,
  `RANK_ID` INT NOT NULL,
  `SHOWS_ID` INT NOT NULL,
  `COMMENT` VARCHAR(100) NULL,
  `ADD_DATE` DATETIME NOT NULL,
  `TIMESTAMP` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`, `DIVISION_ID`, `RANK_ID`, `SHOWS_ID`),
  INDEX `fk_PLACEMENT_DIVISION1_idx` (`DIVISION_ID` ASC),
  INDEX `fk_PLACEMENT_PERSON_MODEL1_idx` (`PERSON_MODEL_ID` ASC),
  INDEX `fk_PLACEMENT_RANK1_idx` (`RANK_ID` ASC),
  INDEX `fk_PLACEMENT_SHOWS1_idx` (`SHOWS_ID` ASC),
  CONSTRAINT `fk_PLACEMENT_DIVISION1`
    FOREIGN KEY (`DIVISION_ID`)
    REFERENCES `frithi_HORSESHOW`.`DIVISION` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PLACEMENT_PERSON_MODEL1`
    FOREIGN KEY (`PERSON_MODEL_ID`)
    REFERENCES `frithi_HORSESHOW`.`PERSON_MODEL` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PLACEMENT_RANK1`
    FOREIGN KEY (`RANK_ID`)
    REFERENCES `frithi_HORSESHOW`.`RANK` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PLACEMENT_SHOWS1`
    FOREIGN KEY (`SHOWS_ID`)
    REFERENCES `frithi_HORSESHOW`.`SHOWS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frithi_HORSESHOW`.`IMAGE_TYPE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frithi_HORSESHOW`.`IMAGE_TYPE` ;

CREATE TABLE IF NOT EXISTS `frithi_HORSESHOW`.`IMAGE_TYPE` (
  `ID` INT NOT NULL,
  `NAME` VARCHAR(45) NOT NULL,
  `DESCRIPTION` VARCHAR(45) NULL,
  `ADD_DATE` VARCHAR(45) NOT NULL,
  `TIMESTAMP` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frithi_HORSESHOW`.`IMAGE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frithi_HORSESHOW`.`IMAGE` ;

CREATE TABLE IF NOT EXISTS `frithi_HORSESHOW`.`IMAGE` (
  `ID` INT NOT NULL,
  `NAME` VARCHAR(45) NULL,
  `DESCRIPTION` VARCHAR(45) NULL,
  `IMAGE` BLOB NULL,
  `FILE_SIZE` VARCHAR(45) NULL,
  `ADD_DATE` VARCHAR(45) NULL,
  `IMAGE_TYPE_ID` INT NOT NULL,
  `FILE_LOAD_STATUS_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `IMAGE_TYPE_ID`),
  INDEX `fk_IMAGE_IMAGE_TYPE1_idx` (`IMAGE_TYPE_ID` ASC),
  INDEX `fk_IMAGE_FILE_LOAD_STATUS1_idx` (`FILE_LOAD_STATUS_ID` ASC),
  CONSTRAINT `fk_IMAGE_IMAGE_TYPE1`
    FOREIGN KEY (`IMAGE_TYPE_ID`)
    REFERENCES `frithi_HORSESHOW`.`IMAGE_TYPE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_IMAGE_FILE_LOAD_STATUS1`
    FOREIGN KEY (`FILE_LOAD_STATUS_ID`)
    REFERENCES `frithi_HORSESHOW`.`FILE_LOAD_STATUS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frithi_HORSESHOW`.`USER_PRIVILEGES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frithi_HORSESHOW`.`USER_PRIVILEGES` ;

CREATE TABLE IF NOT EXISTS `frithi_HORSESHOW`.`USER_PRIVILEGES` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NOT NULL,
  `DESCRIPTION` VARCHAR(45) NOT NULL,
  `ADD_DATE` DATETIME NOT NULL,
  `INACTIVE_DATE` DATETIME NULL,
  `TIMESTAMP` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frithi_HORSESHOW`.`ISSUE_STATUS_TYPE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frithi_HORSESHOW`.`ISSUE_STATUS_TYPE` ;

CREATE TABLE IF NOT EXISTS `frithi_HORSESHOW`.`ISSUE_STATUS_TYPE` (
  `ID` INT NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frithi_HORSESHOW`.`ISSUE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frithi_HORSESHOW`.`ISSUE` ;

CREATE TABLE IF NOT EXISTS `frithi_HORSESHOW`.`ISSUE` (
  `ID` INT NOT NULL,
  `ISSUE_STATUS_TYPE_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `ISSUE_STATUS_TYPE_ID`),
  INDEX `fk_ISSUE_ISSUE_STATUS_TYPE1_idx` (`ISSUE_STATUS_TYPE_ID` ASC),
  CONSTRAINT `fk_ISSUE_ISSUE_STATUS_TYPE1`
    FOREIGN KEY (`ISSUE_STATUS_TYPE_ID`)
    REFERENCES `frithi_HORSESHOW`.`ISSUE_STATUS_TYPE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frithi_HORSESHOW`.`ISSUE_TYPE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frithi_HORSESHOW`.`ISSUE_TYPE` ;

CREATE TABLE IF NOT EXISTS `frithi_HORSESHOW`.`ISSUE_TYPE` (
  `ID` INT NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frithi_HORSESHOW`.`MODEL_has_IMAGE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frithi_HORSESHOW`.`MODEL_has_IMAGE` ;

CREATE TABLE IF NOT EXISTS `frithi_HORSESHOW`.`MODEL_has_IMAGE` (
  `MODEL_ID` INT NOT NULL,
  `MODEL_PERSON_ID` INT NOT NULL,
  `IMAGE_ID` INT NOT NULL,
  `COMMENT` VARCHAR(100) NULL,
  `ADD_DATE` DATETIME NOT NULL,
  `INACTIVE_DATE` DATETIME NULL,
  `TIMESTAMP` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`MODEL_ID`, `MODEL_PERSON_ID`, `IMAGE_ID`),
  INDEX `fk_MODEL_has_IMAGE_IMAGE1_idx` (`IMAGE_ID` ASC),
  INDEX `fk_MODEL_has_IMAGE_MODEL1_idx` (`MODEL_ID` ASC, `MODEL_PERSON_ID` ASC),
  CONSTRAINT `fk_MODEL_has_IMAGE_MODEL1`
    FOREIGN KEY (`MODEL_ID` , `MODEL_PERSON_ID`)
    REFERENCES `frithi_HORSESHOW`.`PERSON_MODEL` (`ID` , `PERSON_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MODEL_has_IMAGE_IMAGE1`
    FOREIGN KEY (`IMAGE_ID`)
    REFERENCES `frithi_HORSESHOW`.`IMAGE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frithi_HORSESHOW`.`HORSESHOW_has_IMAGE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frithi_HORSESHOW`.`HORSESHOW_has_IMAGE` ;

CREATE TABLE IF NOT EXISTS `frithi_HORSESHOW`.`HORSESHOW_has_IMAGE` (
  `HORSESHOW_ID` INT NOT NULL,
  `IMAGE_ID` INT NOT NULL,
  `IMAGE_IMAGE_TYPE_ID` INT NOT NULL,
  `TIMESTAMP` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`HORSESHOW_ID`, `IMAGE_ID`, `IMAGE_IMAGE_TYPE_ID`),
  INDEX `fk_HORSESHOW_has_IMAGE_IMAGE1_idx` (`IMAGE_ID` ASC, `IMAGE_IMAGE_TYPE_ID` ASC),
  INDEX `fk_HORSESHOW_has_IMAGE_HORSESHOW1_idx` (`HORSESHOW_ID` ASC),
  CONSTRAINT `fk_HORSESHOW_has_IMAGE_HORSESHOW1`
    FOREIGN KEY (`HORSESHOW_ID`)
    REFERENCES `frithi_HORSESHOW`.`HORSESHOW` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_HORSESHOW_has_IMAGE_IMAGE1`
    FOREIGN KEY (`IMAGE_ID` , `IMAGE_IMAGE_TYPE_ID`)
    REFERENCES `frithi_HORSESHOW`.`IMAGE` (`ID` , `IMAGE_TYPE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frithi_HORSESHOW`.`HORSESHOW_has_DOCUMENT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frithi_HORSESHOW`.`HORSESHOW_has_DOCUMENT` ;

CREATE TABLE IF NOT EXISTS `frithi_HORSESHOW`.`HORSESHOW_has_DOCUMENT` (
  `HORSESHOW_ID` INT NOT NULL,
  `DOCUMENT_ID` INT NOT NULL,
  `DOCUMENT_DOCUMENT_TYPE_ID` INT NOT NULL,
  `TIMESTAMP` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`HORSESHOW_ID`, `DOCUMENT_ID`, `DOCUMENT_DOCUMENT_TYPE_ID`),
  INDEX `fk_HORSESHOW_has_DOCUMENT_DOCUMENT1_idx` (`DOCUMENT_ID` ASC, `DOCUMENT_DOCUMENT_TYPE_ID` ASC),
  INDEX `fk_HORSESHOW_has_DOCUMENT_HORSESHOW1_idx` (`HORSESHOW_ID` ASC),
  CONSTRAINT `fk_HORSESHOW_has_DOCUMENT_HORSESHOW1`
    FOREIGN KEY (`HORSESHOW_ID`)
    REFERENCES `frithi_HORSESHOW`.`HORSESHOW` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_HORSESHOW_has_DOCUMENT_DOCUMENT1`
    FOREIGN KEY (`DOCUMENT_ID` , `DOCUMENT_DOCUMENT_TYPE_ID`)
    REFERENCES `frithi_HORSESHOW`.`DOCUMENT` (`ID` , `DOCUMENT_TYPE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frithi_HORSESHOW`.`SHOW_REGISTRATION_STATUS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frithi_HORSESHOW`.`SHOW_REGISTRATION_STATUS` ;

CREATE TABLE IF NOT EXISTS `frithi_HORSESHOW`.`SHOW_REGISTRATION_STATUS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NOT NULL,
  `DESCRIPTION` VARCHAR(100) NULL,
  `ADD_DATE` DATETIME NOT NULL,
  `TIMESTAMP` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frithi_HORSESHOW`.`SHOW_REGISTRATION_LINK`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frithi_HORSESHOW`.`SHOW_REGISTRATION_LINK` ;

CREATE TABLE IF NOT EXISTS `frithi_HORSESHOW`.`SHOW_REGISTRATION_LINK` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `SHOW_ID` INT NOT NULL,
  `PERSON_ID` INT NOT NULL,
  `SHOW_REGISTRATION_STATUS_ID` INT NOT NULL,
  `EXHIBITOR_ID` VARCHAR(45) NOT NULL,
  `COMMENT` VARCHAR(45) NULL,
  `DATE_ADD` DATETIME NOT NULL,
  `TIMESTAMP` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`, `SHOW_ID`, `PERSON_ID`, `SHOW_REGISTRATION_STATUS_ID`),
  INDEX `fk_SHOW_REGISTRATION_LINK_SHOW1_idx` (`SHOW_ID` ASC),
  INDEX `fk_SHOW_REGISTRATION_LINK_PERSON1_idx` (`PERSON_ID` ASC),
  INDEX `fk_SHOW_REGISTRATION_LINK_SHOW_REGISTRATION_STATUS1_idx` (`SHOW_REGISTRATION_STATUS_ID` ASC),
  CONSTRAINT `fk_SHOW_REGISTRATION_LINK_SHOW1`
    FOREIGN KEY (`SHOW_ID`)
    REFERENCES `frithi_HORSESHOW`.`SHOWS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SHOW_REGISTRATION_LINK_PERSON1`
    FOREIGN KEY (`PERSON_ID`)
    REFERENCES `frithi_HORSESHOW`.`PERSON` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SHOW_REGISTRATION_LINK_SHOW_REGISTRATION_STATUS1`
    FOREIGN KEY (`SHOW_REGISTRATION_STATUS_ID`)
    REFERENCES `frithi_HORSESHOW`.`SHOW_REGISTRATION_STATUS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frithi_HORSESHOW`.`SHOW_has_IMAGE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frithi_HORSESHOW`.`SHOW_has_IMAGE` ;

CREATE TABLE IF NOT EXISTS `frithi_HORSESHOW`.`SHOW_has_IMAGE` (
  `SHOW_ID` INT NOT NULL,
  `IMAGE_ID` INT NOT NULL,
  `COMMENT` VARCHAR(100) NULL,
  `ADD_DATE` DATETIME NOT NULL,
  PRIMARY KEY (`SHOW_ID`, `IMAGE_ID`),
  INDEX `fk_SHOW_has_IMAGE_IMAGE1_idx` (`IMAGE_ID` ASC),
  INDEX `fk_SHOW_has_IMAGE_SHOW1_idx` (`SHOW_ID` ASC),
  CONSTRAINT `fk_SHOW_has_IMAGE_SHOW1`
    FOREIGN KEY (`SHOW_ID`)
    REFERENCES `frithi_HORSESHOW`.`SHOWS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SHOW_has_IMAGE_IMAGE1`
    FOREIGN KEY (`IMAGE_ID`)
    REFERENCES `frithi_HORSESHOW`.`IMAGE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frithi_HORSESHOW`.`USER_ROLE_has_USER_PRIVILEGES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frithi_HORSESHOW`.`USER_ROLE_has_USER_PRIVILEGES` ;

CREATE TABLE IF NOT EXISTS `frithi_HORSESHOW`.`USER_ROLE_has_USER_PRIVILEGES` (
  `USER_ROLE_ID` INT NOT NULL,
  `USER_PRIVILEGES_ID` INT NOT NULL,
  `ADD_DATE` DATETIME NOT NULL,
  `INACTIVE_DATE` DATETIME NULL,
  `TIMESTAMP` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`USER_ROLE_ID`, `USER_PRIVILEGES_ID`),
  INDEX `fk_USER_ROLE_has_USER_PRIVILEGES_USER_PRIVILEGES1_idx` (`USER_PRIVILEGES_ID` ASC),
  INDEX `fk_USER_ROLE_has_USER_PRIVILEGES_USER_ROLE1_idx` (`USER_ROLE_ID` ASC),
  CONSTRAINT `fk_USER_ROLE_has_USER_PRIVILEGES_USER_ROLE1`
    FOREIGN KEY (`USER_ROLE_ID`)
    REFERENCES `frithi_HORSESHOW`.`USER_ROLE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USER_ROLE_has_USER_PRIVILEGES_USER_PRIVILEGES1`
    FOREIGN KEY (`USER_PRIVILEGES_ID`)
    REFERENCES `frithi_HORSESHOW`.`USER_PRIVILEGES` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frithi_HORSESHOW`.`USER_PROFILE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frithi_HORSESHOW`.`USER_PROFILE` ;

CREATE TABLE IF NOT EXISTS `frithi_HORSESHOW`.`USER_PROFILE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `USER_ID` INT NOT NULL,
  `FIRST_NAME` VARCHAR(60) NOT NULL,
  `MIDDLE_NAME` VARCHAR(60) NULL,
  `LAST_NAME` VARCHAR(60) NULL,
  `SUFFIX` VARCHAR(60) NULL,
  `GENDER` VARCHAR(10) NULL,
  `NICKNAME` VARCHAR(60) NULL,
  `ADDRESS_LINE_1` VARCHAR(75) NULL,
  `ADDRESS_LINE_2` VARCHAR(75) NULL,
  `ADDRESS_LINE_3` VARCHAR(75) NULL,
  `CITY` VARCHAR(45) NULL,
  `STATE` CHAR(2) NULL,
  `ZIP` VARCHAR(20) NULL,
  `PHONE_NBR_HOME` CHAR(10) NULL,
  `PHONE_NBR_CELL` CHAR(10) NULL,
  `PHONE_NBR_ALT` CHAR(10) NULL,
  `ADD_DATE` DATETIME NOT NULL,
  `COMMENT` VARCHAR(100) NULL,
  `MAILING_LIST` CHAR NOT NULL DEFAULT 'Y',
  PRIMARY KEY (`ID`, `USER_ID`),
  INDEX `fk_USER_PROFILE_USER1_idx` (`USER_ID` ASC),
  UNIQUE INDEX `USER_ID_UNIQUE` (`USER_ID` ASC),
  CONSTRAINT `fk_USER_PROFILE_USER1`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `frithi_HORSESHOW`.`USER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frithi_HORSESHOW`.`HORSESHOW_USER_TYPE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frithi_HORSESHOW`.`HORSESHOW_USER_TYPE` ;

CREATE TABLE IF NOT EXISTS `frithi_HORSESHOW`.`HORSESHOW_USER_TYPE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(75) NOT NULL,
  `DESCRIPTION` VARCHAR(100) NULL,
  `ADD_DATE` DATETIME NOT NULL,
  `INACTIVE_DATE` DATETIME NULL,
  `TIMESTAMP` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frithi_HORSESHOW`.`USER_has_HORSESHOW`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frithi_HORSESHOW`.`USER_has_HORSESHOW` ;

CREATE TABLE IF NOT EXISTS `frithi_HORSESHOW`.`USER_has_HORSESHOW` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `USER_ID` INT NOT NULL,
  `HORSESHOW_ID` INT NOT NULL,
  `HORSESHOW_USER_TYPE_ID` INT NOT NULL,
  `COMMENT` VARCHAR(100) NULL,
  `DATE_ADD` DATETIME NOT NULL,
  `TIMESTAMP` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`, `USER_ID`, `HORSESHOW_ID`, `HORSESHOW_USER_TYPE_ID`),
  INDEX `fk_USER_has_HORSESHOW_HORSESHOW1_idx` (`HORSESHOW_ID` ASC),
  INDEX `fk_USER_has_HORSESHOW_USER1_idx` (`USER_ID` ASC),
  INDEX `fk_USER_has_HORSESHOW_HORSESHOW_USER_TYPE1_idx` (`HORSESHOW_USER_TYPE_ID` ASC),
  CONSTRAINT `fk_USER_has_HORSESHOW_USER1`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `frithi_HORSESHOW`.`USER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USER_has_HORSESHOW_HORSESHOW1`
    FOREIGN KEY (`HORSESHOW_ID`)
    REFERENCES `frithi_HORSESHOW`.`HORSESHOW` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USER_has_HORSESHOW_HORSESHOW_USER_TYPE1`
    FOREIGN KEY (`HORSESHOW_USER_TYPE_ID`)
    REFERENCES `frithi_HORSESHOW`.`HORSESHOW_USER_TYPE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frithi_HORSESHOW`.`USER_MODEL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frithi_HORSESHOW`.`USER_MODEL` ;

CREATE TABLE IF NOT EXISTS `frithi_HORSESHOW`.`USER_MODEL` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `USER_ID` INT NOT NULL,
  `MODEL_TYPE_ID` INT NOT NULL,
  `BREED_ID` INT NULL,
  `BREED_NAME` VARCHAR(100) NULL,
  `NAME` VARCHAR(100) NOT NULL,
  `COMMENT` VARCHAR(45) NULL,
  `DESCRIPTION` VARCHAR(100) NULL,
  `TIMESTAMP` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`, `USER_ID`, `MODEL_TYPE_ID`),
  INDEX `fk_table1_USER1_idx` (`USER_ID` ASC),
  INDEX `fk_table1_BREED1_idx` (`BREED_ID` ASC),
  INDEX `fk_table1_MODEL_TYPE1_idx` (`MODEL_TYPE_ID` ASC),
  CONSTRAINT `fk_table1_USER1`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `frithi_HORSESHOW`.`USER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table1_BREED1`
    FOREIGN KEY (`BREED_ID`)
    REFERENCES `frithi_HORSESHOW`.`BREED` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table1_MODEL_TYPE1`
    FOREIGN KEY (`MODEL_TYPE_ID`)
    REFERENCES `frithi_HORSESHOW`.`MODEL_TYPE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frithi_HORSESHOW`.`LOG`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frithi_HORSESHOW`.`LOG` ;

CREATE TABLE IF NOT EXISTS `frithi_HORSESHOW`.`LOG` (
  `ID` INT NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

USE `frithi_HORSESHOW_WEBSITE` ;

-- -----------------------------------------------------
-- Table `frithi_HORSESHOW_WEBSITE`.`CONTENT_TYPE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frithi_HORSESHOW_WEBSITE`.`CONTENT_TYPE` ;

CREATE TABLE IF NOT EXISTS `frithi_HORSESHOW_WEBSITE`.`CONTENT_TYPE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NOT NULL,
  `VAR_CODE` VARCHAR(10) NOT NULL,
  `DESCRIPTION` VARCHAR(100) NULL,
  `DATE_ADD` DATETIME NOT NULL,
  `TIMESTAMP` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frithi_HORSESHOW_WEBSITE`.`CONTENT_CATEGORY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frithi_HORSESHOW_WEBSITE`.`CONTENT_CATEGORY` ;

CREATE TABLE IF NOT EXISTS `frithi_HORSESHOW_WEBSITE`.`CONTENT_CATEGORY` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NOT NULL,
  `VAR_CODE` VARCHAR(10) NOT NULL,
  `DESCRIPTION` VARCHAR(100) NULL,
  `DATE_ADD` DATETIME NULL,
  `TIMESTAMP` TIMESTAMP NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frithi_HORSESHOW_WEBSITE`.`CONTENT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frithi_HORSESHOW_WEBSITE`.`CONTENT` ;

CREATE TABLE IF NOT EXISTS `frithi_HORSESHOW_WEBSITE`.`CONTENT` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CONTENT_TYPE_ID` INT NOT NULL,
  `CATEGORY_ID` INT NOT NULL,
  `USER_ID` INT NULL,
  `TITLE` VARCHAR(45) NULL,
  `TEXT` TEXT NOT NULL,
  `AUTHOR` VARCHAR(45) NOT NULL,
  `DATE_ADD` DATETIME NOT NULL,
  `INACTIVE_DATE` DATETIME NULL,
  `TIMESTAMP` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`, `CONTENT_TYPE_ID`, `CATEGORY_ID`),
  INDEX `fk_CONTENT_CONTENT_TYPE1_idx` (`CONTENT_TYPE_ID` ASC),
  INDEX `fk_CONTENT_CATEGORY1_idx` (`CATEGORY_ID` ASC),
  INDEX `fk_CONTENT_USER1_idx` (`USER_ID` ASC),
  CONSTRAINT `fk_CONTENT_CONTENT_TYPE1`
    FOREIGN KEY (`CONTENT_TYPE_ID`)
    REFERENCES `frithi_HORSESHOW_WEBSITE`.`CONTENT_TYPE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CONTENT_CATEGORY1`
    FOREIGN KEY (`CATEGORY_ID`)
    REFERENCES `frithi_HORSESHOW_WEBSITE`.`CONTENT_CATEGORY` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CONTENT_USER1`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `frithi_HORSESHOW`.`USER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
