delete from horseshow.BREED;
insert into horseshow.BREED values (1,null,'Abaco Barb','Mixed Spanish Breeds and Spanish Types',NOW());
insert into horseshow.BREED values (2,null,'Abtenauer','Other Pure/Rare Horse(Germany)',NOW());
insert into horseshow.BREED values (3,null,'Abyssinian','Other Pure/Rare Horse (Ethiopia)',NOW());
insert into horseshow.BREED values (4,null,'Adayev','Kirghiz',NOW());
insert into horseshow.BREED values (5,null,'Aegidienberger','Other Pure/Rare Horse (Germany)',NOW());
insert into horseshow.BREED values (6,null,'Akhal','Teke',NOW());
insert into horseshow.BREED values (7,null,'Albanian','Other Pure/Rare Pony (Balkan Peninsula)',NOW());
insert into horseshow.BREED values (8,null,'Albino','Color Breeds/Other Pure Stock',NOW());
insert into horseshow.BREED values (9,null,'Altai','Other Pure/Rare Horse (Altai Mountains/Asia)',NOW());
insert into horseshow.BREED values (10,null,'Alter','Real',NOW());
insert into horseshow.BREED values (11,null,'American (Bashkir) Curly Horse','see Bashkir Curly',NOW());
insert into horseshow.BREED values (12,null,'American Cream Draft','Color Breeds/Other Pure Stock',NOW());
insert into horseshow.BREED values (13,null,'American Cream','Other Pure Draft',NOW());
insert into horseshow.BREED values (14,null,'American Indian Horse/Pony','Native North American Breeds',NOW());
insert into horseshow.BREED values (15,null,'American Mustang','Mustangs',NOW());
insert into horseshow.BREED values (16,null,'American Shetland pony','North American Pony',NOW());
insert into horseshow.BREED values (17,null,'American Spotted Draft','Other Pure Draft',NOW());
insert into horseshow.BREED values (18,null,'American Sulphur Horse','shows with Spanish Sulpher Horse',NOW());
insert into horseshow.BREED values (19,null,'American Walking Pony','North American Pony',NOW());
insert into horseshow.BREED values (20,null,'Anadolu (aka Ati)','Other Pure/Rare Pony (Turkey)',NOW());
insert into horseshow.BREED values (21,null,'Andalusian','named breed class',NOW());
insert into horseshow.BREED values (22,null,'Andravida','Other Pure/Rare Horse (Greece)',NOW());
insert into horseshow.BREED values (23,null,'Anglo','Arab',NOW());
insert into horseshow.BREED values (24,null,'Anglo','Kabarda',NOW());
insert into horseshow.BREED values (25,null,'Appalachian Singlefoot','Native North American Breeds',NOW());
insert into horseshow.BREED values (26,null,'Appaloosa','named breed class',NOW());
insert into horseshow.BREED values (27,null,'Appendix Quarter Horse','Quarter Horse',NOW());
insert into horseshow.BREED values (28,null,'Arabian','named breed class',NOW());
insert into horseshow.BREED values (29,null,'Ardennes','French draft',NOW());
insert into horseshow.BREED values (30,null,'Arenberg','Nordkirchen',NOW());
insert into horseshow.BREED values (31,null,'Ariegeois pony','European pony (France)',NOW());
insert into horseshow.BREED values (32,null,'Asian/Asiatic Wild Horse','Primitives',NOW());
insert into horseshow.BREED values (33,null,'Assateague pony','North American Pony',NOW());
insert into horseshow.BREED values (34,null,'Astercon pony (aka Asturian & Galician)','European Pony (Spain)',NOW());
insert into horseshow.BREED values (35,null,'Asturian pony (aka Astercon & Galician)','European Pony (Spain)',NOW());
insert into horseshow.BREED values (36,null,'Ati (aka Anadolu)','Other Pure/Rare Pony (Turkey)',NOW());
insert into horseshow.BREED values (37,null,'Australian Brumby','Other Pure/Rare Horse (Australia)',NOW());
insert into horseshow.BREED values (38,null,'Australian Pony','Australian Pony',NOW());
insert into horseshow.BREED values (39,null,'Australian Stock Horse','Other Pure Stock',NOW());
insert into horseshow.BREED values (40,null,'Australian Waler','Other Pure/Rare Horse (Australia)',NOW());
insert into horseshow.BREED values (41,null,'Austrian Warmblood','Other European Warmblood (Austria)',NOW());
insert into horseshow.BREED values (42,null,'Auxios','French draft',NOW());
insert into horseshow.BREED values (43,null,'Avelignese pony','',NOW());
insert into horseshow.BREED values (44,null,'Azteca','Other Iberian Breeds (Mexico)',NOW());
insert into horseshow.BREED values (45,null,'Baise','see Guangxi',NOW());
insert into horseshow.BREED values (46,null,'Balearic','Other Pure/Rare Pony (Majorca/Spain)',NOW());
insert into horseshow.BREED values (47,null,'Balikun','Other Pure/Rare Horse (China)',NOW());
insert into horseshow.BREED values (48,null,'Balis','Primitives',NOW());
insert into horseshow.BREED values (49,null,'Baluchi','Other Pure/Rare Horse Breeds (Pakistan)',NOW());
insert into horseshow.BREED values (50,null,'Ban','ei',NOW());
insert into horseshow.BREED values (51,null,'Banker Pony (aka Shackleford)','North American Pony (US)',NOW());
insert into horseshow.BREED values (52,null,'Barb','Part Arabian',NOW());
insert into horseshow.BREED values (53,null,'Bardigiano pony','European Pony (Italy)',NOW());
insert into horseshow.BREED values (54,null,'Barthais','see Landais Pony',NOW());
insert into horseshow.BREED values (55,null,'Bashkir Curly','Other Pure Stock',NOW());
insert into horseshow.BREED values (56,null,'Bashkir pony','European Pony (Russia)',NOW());
insert into horseshow.BREED values (57,null,'Basotho (aka Basuto)','African Pony (South Africa)',NOW());
insert into horseshow.BREED values (58,null,'Basque pony (aka Pottock)','European Pony (France/Spain)',NOW());
insert into horseshow.BREED values (59,null,'Basuto pony (aka Basotho)','African Pony (South Africa)',NOW());
insert into horseshow.BREED values (60,null,'Batak pony','Asian Pony (Indonesia)',NOW());
insert into horseshow.BREED values (61,null,'Bavarian Warmblood','German Warmblood',NOW());
insert into horseshow.BREED values (62,null,'Beberbeck','Other Pure/Rare Horse Breeds (German)',NOW());
insert into horseshow.BREED values (63,null,'Belgian (aka Brabant)','European draft (Belgium)',NOW());
insert into horseshow.BREED values (64,null,'Belgian Warmblood','Other European Warmblood (Belgium)',NOW());
insert into horseshow.BREED values (65,null,'Bhutia (aka Spiti) pony','Asian Pony (India)',NOW());
insert into horseshow.BREED values (66,null,'Black Forest Horse (aka Noriker)','European draft (German)',NOW());
insert into horseshow.BREED values (67,null,'Boer (aka Boerperd)','Other Pure/Rare Horse (South Africa)',NOW());
insert into horseshow.BREED values (68,null,'Boerperd (aka Boer)','Other Pure/Rare Horse (South Africa)',NOW());
insert into horseshow.BREED values (69,null,'Bosnian pony','European pony (former Yugoslavia)',NOW());
insert into horseshow.BREED values (70,null,'Boulonnais','French draft',NOW());
insert into horseshow.BREED values (71,null,'Brabant (aka Belgian)','European draft (Belgian)',NOW());
insert into horseshow.BREED values (72,null,'Brandenburger','German Warmblood',NOW());
insert into horseshow.BREED values (73,null,'Brazilian Sporthorse','Other Pure/Mixed Sport Horse Breeds (Brazil)',NOW());
insert into horseshow.BREED values (74,null,'Breton','French draft',NOW());
insert into horseshow.BREED values (75,null,'Brumby','see Australian Brumby',NOW());
insert into horseshow.BREED values (76,null,'Buckskin','Color Breeds/Mixed Stock (when shown as a "registered" type)',NOW());
insert into horseshow.BREED values (77,null,'Budyonny','Other European Warmblood (Russia)',NOW());
insert into horseshow.BREED values (78,null,'Buluchi','Other Pure/Rare Horse (Pakistan)',NOW());
insert into horseshow.BREED values (79,null,'Burmese pony (aka Shan)','Asian Pony (Burma)',NOW());
insert into horseshow.BREED values (80,null,'Burros','Primitives',NOW());
insert into horseshow.BREED values (81,null,'Byelorussian Harness Horse','Carriage & Driving breeds (Belarus)',NOW());
insert into horseshow.BREED values (82,null,'Calabrese','Other Pure/Rare Horse (Italy)',NOW());
insert into horseshow.BREED values (83,null,'Camargue pony','European pony (France)',NOW());
insert into horseshow.BREED values (84,null,'Camarillo White Horse','Native North American Breeds',NOW());
insert into horseshow.BREED values (85,null,'Campolina','Other Pure/Rare Horse',NOW());
insert into horseshow.BREED values (86,null,'Canadian Cutting Horse','Native North American Breeds',NOW());
insert into horseshow.BREED values (87,null,'Canadian Horse','Native North American Breeds',NOW());
insert into horseshow.BREED values (88,null,'Canadian Pacer','Harness Racing Breeds',NOW());
insert into horseshow.BREED values (89,null,'Carolina Marsh Tacky','Native North American Breeds',NOW());
insert into horseshow.BREED values (90,null,'Carpathian pony (aka Hucul)','European Pony (Poland)',NOW());
insert into horseshow.BREED values (91,null,'Carthusian (aka Cartujano)','Other Iberian Breeds (Spain)',NOW());
insert into horseshow.BREED values (92,null,'Cartujano (aka Carthusian)','Other Iberian Breeds (Spain)',NOW());
insert into horseshow.BREED values (93,null,'Caspian pony','European pony (Iran)',NOW());
insert into horseshow.BREED values (94,null,'Castilian','Other Iberian Breeds (Iberian Peninsula)',NOW());
insert into horseshow.BREED values (95,null,'Cayuse (Indian Pony)','Native North American Breeds',NOW());
insert into horseshow.BREED values (96,null,'Cerbat','Other Pure/Rare Horse Breeds (North America)',NOW());
insert into horseshow.BREED values (97,null,'Cheju','Other Pure/Rare Pony (Korea)',NOW());
insert into horseshow.BREED values (98,null,'Chicksaw (Indian Pony)','Native North American Breeds',NOW());
insert into horseshow.BREED values (99,null,'Chilean Corralero','Other Iberian Breeds (Chile)',NOW());
insert into horseshow.BREED values (100,null,'Chilean Horse','Other Iberian Breeds (Chile)',NOW());
insert into horseshow.BREED values (101,null,'Chilote','Other Pure/Rare Horse Breeds (Chile)',NOW());
insert into horseshow.BREED values (102,null,'Chincoteague pony','North American Pony (U.S.)',NOW());
insert into horseshow.BREED values (103,null,'Chinese Guoxia pony','Asian Pony (China)',NOW());
insert into horseshow.BREED values (104,null,'Choctaw (Indian Pony)','Native North American Breeds',NOW());
insert into horseshow.BREED values (105,null,'Cleveland Bay','Carriage & Driving breeds (England)',NOW());
insert into horseshow.BREED values (106,null,'Clydesdale','Other U.K. draft (Scotland)',NOW());
insert into horseshow.BREED values (107,null,'Colonial Spanish Horse','Other Iberian Breeds (Spain)',NOW());
insert into horseshow.BREED values (108,null,'Colorado Ranger','Native North American Breeds',NOW());
insert into horseshow.BREED values (109,null,'Comtois','French draft',NOW());
insert into horseshow.BREED values (110,null,'Connemara pony','Other U.K. Pony (Ireland)',NOW());
insert into horseshow.BREED values (111,null,'Costarricense de Paso','Other Iberian Breeds (Costa Rica)',NOW());
insert into horseshow.BREED values (112,null,'Cretan Horse','Other Pure/Rare Horse (Crete)',NOW());
insert into horseshow.BREED values (113,null,'Criollo','Other Iberian Breeds (Argentina)',NOW());
insert into horseshow.BREED values (114,null,'Cruzado','Other Pure/Rare Horse Breeds (Germany)',NOW());
insert into horseshow.BREED values (115,null,'Cuban Trotter (aka Criollo de Trote)','Harness Racing Breeds',NOW());
insert into horseshow.BREED values (116,null,'Czech Warmblood','Other European Warmblood (Czech Republic)',NOW());
insert into horseshow.BREED values (117,null,'Dales pony','Other U.K. Pony (England)',NOW());
insert into horseshow.BREED values (118,null,'Danish Warmblood','Other European Warmblood (Denmark)',NOW());
insert into horseshow.BREED values (119,null,'Danubian','Other Pure/Rare Horse (Bulgaria)',NOW());
insert into horseshow.BREED values (120,null,'Darashouri (aka Shirazi)','Arabian Types',NOW());
insert into horseshow.BREED values (121,null,'Dartmoor pony','Other U.K. Pony (England)',NOW());
insert into horseshow.BREED values (122,null,'Deliboz','Other Pure/Rare Horse (Azerbaijan)',NOW());
insert into horseshow.BREED values (123,null,'Djerma','Other Pure/Rare Horse (Niger/West Africa)',NOW());
insert into horseshow.BREED values (124,null,'Dolahest (aka Dole Gudbrandsal & Dole)','Carriage & Driving (Norway)',NOW());
insert into horseshow.BREED values (125,null,'Dole (aka Dole Gudbrandsal & Dolahest)','Carriage & Driving (Norway)',NOW());
insert into horseshow.BREED values (126,null,'Dole Gudbrandsal (aka Dole & Dolahest)','Carriage & Driving (Norway)',NOW());
insert into horseshow.BREED values (127,null,'Dongola','Other Pure/Rare Horse (West Africa)',NOW());
insert into horseshow.BREED values (128,null,'Drum Horse','Other Pure/Mixed Draft',NOW());
insert into horseshow.BREED values (129,null,'Dulmen pony','European Pony (Germany)',NOW());
insert into horseshow.BREED values (130,null,'Dutch Harness Horse (aka Tuigpaard)','Carriage & Driving (Netherlands)',NOW());
insert into horseshow.BREED values (131,null,'Dutch Heavy Draft','European draft (Netherlands)',NOW());
insert into horseshow.BREED values (132,null,'Dutch Warmblood','Other European Warmblood (Netherlands)',NOW());
insert into horseshow.BREED values (133,null,'East Bulgarian','Part Arabian',NOW());
insert into horseshow.BREED values (134,null,'East Fresian','Carriage & Driving breeds (Germany)',NOW());
insert into horseshow.BREED values (135,null,'Egyptian Arabian','Arabian Types',NOW());
insert into horseshow.BREED values (136,null,'Eriskay','Other Pure/Rare Pony (Scotland)',NOW());
insert into horseshow.BREED values (137,null,'Estonian Draft','European draft (Estonia/Europe)',NOW());
insert into horseshow.BREED values (138,null,'Estonian Native','Other Pure/Rare Horse (Estonia/Europe)',NOW());
insert into horseshow.BREED values (139,null,'Exmoor pony','Other U.K. Pony (England)',NOW());
insert into horseshow.BREED values (140,null,'Extremeno','Other Iberian Breeds (Iberian Peninsula)',NOW());
insert into horseshow.BREED values (141,null,'Faeros','Other Pure/Rare Pony (Faeroe Islands/Europe)',NOW());
insert into horseshow.BREED values (142,null,'Falabella','Mini Pony',NOW());
insert into horseshow.BREED values (143,null,'Fell pony','Other U.K. Pony (England)',NOW());
insert into horseshow.BREED values (144,null,'Finnish Draft','European draft (Finland)',NOW());
insert into horseshow.BREED values (145,null,'Finnish Universal','Other European Warmblood (Finland)',NOW());
insert into horseshow.BREED values (146,null,'Fleuvre (aka Fouta & M’Bayar)','Other Pure/Rare Pony (Senegal/Africa)',NOW());
insert into horseshow.BREED values (147,null,'Flores (aka Timor)','Other Pure/Rare Pony (Indonesia/Asia)',NOW());
insert into horseshow.BREED values (148,null,'Florida Cracker Horse','Native North American Breeds',NOW());
insert into horseshow.BREED values (149,null,'Fouta (aka Fleuvre & M’Bayar)','Other Pure/Rare Pony (Senegal/Africa)',NOW());
insert into horseshow.BREED values (150,null,'Frances','Montagnes (aka Frieberger)',NOW());
insert into horseshow.BREED values (151,null,'Frederiksborg','Other European Warmblood (Denmark)',NOW());
insert into horseshow.BREED values (152,null,'French Anglo','Arab',NOW());
insert into horseshow.BREED values (153,null,'French Saddle Pony','European pony (France)',NOW());
insert into horseshow.BREED values (154,null,'French Trotter','Harness Racing Breeds (France)',NOW());
insert into horseshow.BREED values (155,null,'Fresian','Carriage & Driving breeds (Netherlands)',NOW());
insert into horseshow.BREED values (156,null,'Frieberger (aka Frances','Montagnes)',NOW());
insert into horseshow.BREED values (157,null,'Friewalker','Fresian cross **',NOW());
insert into horseshow.BREED values (158,null,'Furioso','Other Pure/Rare Horse',NOW());
insert into horseshow.BREED values (159,null,'Galiceno pony','South American Pony (Mexico)',NOW());
insert into horseshow.BREED values (160,null,'Galician pony (aka Asturian & Astercon)','European Pony (Spain)',NOW());
insert into horseshow.BREED values (161,null,'Garrano pony','European Pony (Portugal)',NOW());
insert into horseshow.BREED values (162,null,'Gayoe','Other Pure/Rare Pony (Sumatra/Indonesia/Asia)',NOW());
insert into horseshow.BREED values (163,null,'Gelderlander','Carriage & Driving breeds (Netherlands)',NOW());
insert into horseshow.BREED values (164,null,'Georgian Grande','Fresian cross **',NOW());
insert into horseshow.BREED values (165,null,'German Heck Horse','Primitives',NOW());
insert into horseshow.BREED values (166,null,'German Riding Pony','European Pony (Germany)',NOW());
insert into horseshow.BREED values (167,null,'German Warmblood','Other European Warmblood (Germany)',NOW());
insert into horseshow.BREED values (168,null,'Gidran Arab','Arabian',NOW());
insert into horseshow.BREED values (169,null,'Gidran Sport Horse','Other European Warmblood (Hungary)',NOW());
insert into horseshow.BREED values (170,null,'Gotland pony (aka Skogruss)','European Pony (Sweden)',NOW());
insert into horseshow.BREED values (171,null,'Groningen','Carriage & Driving breeds (Netherlands)',NOW());
insert into horseshow.BREED values (172,null,'Guangxi','Other Pure/Rare Pony (China)',NOW());
insert into horseshow.BREED values (173,null,'Guizhou','Other Pure/Rare Pony (China)',NOW());
insert into horseshow.BREED values (174,null,'Gypsy Cob','Carriage & Driving breeds (England)',NOW());
insert into horseshow.BREED values (175,null,'Gypsy Vanner','Carriage & Driving breeds (England)',NOW());
insert into horseshow.BREED values (176,null,'Hackney Horse','Carriage & Driving breeds (England)',NOW());
insert into horseshow.BREED values (177,null,'Hackney pony','Other U.K. Pony (England)',NOW());
insert into horseshow.BREED values (178,null,'Haflinger pony','European Pony (Austria)',NOW());
insert into horseshow.BREED values (179,null,'Hanoverian','German Warmblood',NOW());
insert into horseshow.BREED values (180,null,'Heihe','Other Pure/Rare Horse (China)',NOW());
insert into horseshow.BREED values (181,null,'Henson','Other Pure/Rare Horse Breeds (France)',NOW());
insert into horseshow.BREED values (182,null,'Hequ','Other Pure/Rare Horse (China)',NOW());
insert into horseshow.BREED values (183,null,'Hessen','Other Pure/Rare Horse Breeds (German)',NOW());
insert into horseshow.BREED values (184,null,'Highland pony','Other U.K. Pony (Scotland)',NOW());
insert into horseshow.BREED values (185,null,'Hirzai','Other Pure/Rare Horse (Pakistan/Asia)',NOW());
insert into horseshow.BREED values (186,null,'Hispano','Arab (aka Peninsula Horse & Spanish Anglo',NOW());
insert into horseshow.BREED values (187,null,'Hokkaido','Other Pure/Rare Pony (Japan)',NOW());
insert into horseshow.BREED values (188,null,'Holstein','German Warmblood',NOW());
insert into horseshow.BREED values (189,null,'Hucul pony (aka Carpathian)','European Pony (Poland)',NOW());
insert into horseshow.BREED values (190,null,'Hungarian Warmblood','Other European Warmblood (Hungary)',NOW());
insert into horseshow.BREED values (191,null,'Icelandic pony','European Pony (Iceland)',NOW());
insert into horseshow.BREED values (192,null,'Indian Half','Bred',NOW());
insert into horseshow.BREED values (193,null,'Iomud','Other Pure/Mixed Sport Breeds',NOW());
insert into horseshow.BREED values (194,null,'Irish (Draught) Sport Horse','Other European Warmblood (Ireland)',NOW());
insert into horseshow.BREED values (195,null,'Irish Draft/Draught','Other U.K. draft (Ireland)',NOW());
insert into horseshow.BREED values (196,null,'Irish Draught (non','Draft)',NOW());
insert into horseshow.BREED values (197,null,'Irish Hunter','Other European Warmblood (Ireland)',NOW());
insert into horseshow.BREED values (198,null,'Irish Warmblood','Other European Warmblood (Ireland)',NOW());
insert into horseshow.BREED values (199,null,'Italian Heavy Draft','European draft (Italy)',NOW());
insert into horseshow.BREED values (200,null,'Java pony (aka Kumingan)','Asian Pony (Indonesia)',NOW());
insert into horseshow.BREED values (201,null,'Jinzhou','Other Pure/Rare Horse (China)',NOW());
insert into horseshow.BREED values (202,null,'Jutland','European draft (Denmark)',NOW());
insert into horseshow.BREED values (203,null,'Kabarda (aka Kabardin)','Other Pure/Rare Horse (Stravropol/Russia)',NOW());
insert into horseshow.BREED values (204,null,'Kabardin (aka Kabarda)','Other Pure/Rare Horse (Stravropol/Russia)',NOW());
insert into horseshow.BREED values (205,null,'Kaimanawa','Other Pure/Rare Pony (New Zealand)',NOW());
insert into horseshow.BREED values (206,null,'Karabakh','Arabian',NOW());
insert into horseshow.BREED values (207,null,'Karacabey','Other Pure/Rare Horse (Turkey)',NOW());
insert into horseshow.BREED values (208,null,'Kathiawari','Part Arabian',NOW());
insert into horseshow.BREED values (209,null,'Kazakh pony','Asian Pony (Kazakhstan)',NOW());
insert into horseshow.BREED values (210,null,'Kazakii','Other Pure/Rare Pony Breeds (Mongolia)',NOW());
insert into horseshow.BREED values (211,null,'Kentucky Mountain Saddle Horse','Native North American Breeds',NOW());
insert into horseshow.BREED values (212,null,'Kerry Bog Pony','Other Pure/Rare Pony (Ireland)',NOW());
insert into horseshow.BREED values (213,null,'Kiangas','Primitives',NOW());
insert into horseshow.BREED values (214,null,'Kiger Mustang','Mustangs',NOW());
insert into horseshow.BREED values (215,null,'Kinsky','Other Pure/Rare Horse (Czech Republic)',NOW());
insert into horseshow.BREED values (216,null,'Kirdi','Other Pure/Rare Pony (Camaroon/Africa)',NOW());
insert into horseshow.BREED values (217,null,'Kisber Felver','Other European Warmblood (Hungary)',NOW());
insert into horseshow.BREED values (218,null,'Kiso','Other Pure/Rare Horse (Japan)',NOW());
insert into horseshow.BREED values (219,null,'Kladruber','Carriage & Driving Breeds (Czech Republic)',NOW());
insert into horseshow.BREED values (220,null,'Klepper (aka Torijski)','Other Pure Draft Breeds (Estonia)',NOW());
insert into horseshow.BREED values (221,null,'Knabstrup','Other European Warmblood (Denmark)',NOW());
insert into horseshow.BREED values (222,null,'Konik pony','European Pony (Poland)',NOW());
insert into horseshow.BREED values (223,null,'Kumingan pony (aka Java)','Asian Pony (Indonesia)',NOW());
insert into horseshow.BREED values (224,null,'Kushum','Other Pure/Rare Horse (Kazakhstan/Asia)',NOW());
insert into horseshow.BREED values (225,null,'Kustanair','Other Pure/Rare Horse (Kazakhstan/Asia)',NOW());
insert into horseshow.BREED values (226,null,'Lac La Croix Indian Pony','Native North American Breeds',NOW());
insert into horseshow.BREED values (227,null,'Landais pony','European Pony (France)',NOW());
insert into horseshow.BREED values (228,null,'Latvian','Other Pure/Rare Horse (Latvia/Europe)',NOW());
insert into horseshow.BREED values (229,null,'Latvian Harness Horse','European draft (Latvia/Europe)',NOW());
insert into horseshow.BREED values (230,null,'Latvian Riding Horse','Other Rare Breeds',NOW());
insert into horseshow.BREED values (231,null,'Lewitzer (aka Lewizschecken) Pony','European Pony',NOW());
insert into horseshow.BREED values (232,null,'Lijiang','Other Pure/Rare Pony (China)',NOW());
insert into horseshow.BREED values (233,null,'Lippizzaner','Spanish Types (Slovenia/Austria)',NOW());
insert into horseshow.BREED values (234,null,'Lithuanian Heavy Draft','European draft (Lithuania)',NOW());
insert into horseshow.BREED values (235,null,'Lokai','Other Pure/Rare Horse (Tajikistan/Asia)',NOW());
insert into horseshow.BREED values (236,null,'Losino','Other Pure/Rare Horse (Burgos/Spain)',NOW());
insert into horseshow.BREED values (237,null,'Luisitano','named breed class (Portugal)',NOW());
insert into horseshow.BREED values (238,null,'Lundy pony','Other U.K. Pony (England)',NOW());
insert into horseshow.BREED values (239,null,'Lyngshest (aka Nordlandshest)','Other Pure/Rare Pony (Norway)',NOW());
insert into horseshow.BREED values (240,null,'M’Bayar (aka Fleuvre & Fouta)','Other Pure/Rare Pony (Senegal/Africa)',NOW());
insert into horseshow.BREED values (241,null,'Malapolski','Other European Warmblood (Poland)',NOW());
insert into horseshow.BREED values (242,null,'Manades','see Camargue Pony',NOW());
insert into horseshow.BREED values (243,null,'Manchurian','Other Pure/Rare Pony (Siberia)',NOW());
insert into horseshow.BREED values (244,null,'Mangalarga Marchador','Other Iberian Breeds (Brazil)',NOW());
insert into horseshow.BREED values (245,null,'Manipuri pony','Asian Pony (India)',NOW());
insert into horseshow.BREED values (246,null,'Maremmana','Part Arabian',NOW());
insert into horseshow.BREED values (247,null,'Marwari','Part Arabian',NOW());
insert into horseshow.BREED values (248,null,'McCurdy Plantation Horse','Other Pure Gaited',NOW());
insert into horseshow.BREED values (249,null,'Mecklenburg','German Warmblood',NOW());
insert into horseshow.BREED values (250,null,'Menorquina','Other Iberian Breeds (Menorca/Spain)',NOW());
insert into horseshow.BREED values (251,null,'Merens pony','European Pony (France)',NOW());
insert into horseshow.BREED values (252,null,'Messara','Other Pure/Rare Horse (Crete)',NOW());
insert into horseshow.BREED values (253,null,'Metis Trotter (aka Russian Trotter)','Harness Racing Breeds(Russia)',NOW());
insert into horseshow.BREED values (254,null,'Misaki','Other Pure/Rare Pony (Japan)',NOW());
insert into horseshow.BREED values (255,null,'Missouri Fox Trotter','named breed class',NOW());
insert into horseshow.BREED values (256,null,'Miyako','Other Pure/Rare Horse (Japan)',NOW());
insert into horseshow.BREED values (257,null,'Mongolians','Primitives',NOW());
insert into horseshow.BREED values (258,null,'Montana Traveler','Native North American Breeds',NOW());
insert into horseshow.BREED values (259,null,'Morab','Part Arabian',NOW());
insert into horseshow.BREED values (260,null,'Morgan','named breed class',NOW());
insert into horseshow.BREED values (261,null,'Moriesian','Fresian cross **',NOW());
insert into horseshow.BREED values (262,null,'Moyle','Native North American Breeds',NOW());
insert into horseshow.BREED values (263,null,'Mulassier (aka Poitevin)','French draft',NOW());
insert into horseshow.BREED values (264,null,'Murakozi','European draft (Hungary)',NOW());
insert into horseshow.BREED values (265,null,'Murghese','Other Pure/Rare Horse (Italy)',NOW());
insert into horseshow.BREED values (266,null,'Murinsulan','Other Pure/Rare Horse Breeds (Croatia)',NOW());
insert into horseshow.BREED values (267,null,'Nanfan','see Hequ',NOW());
insert into horseshow.BREED values (268,null,'Napoletano','Other Pure/Rare Horse Breeds (Italy)',NOW());
insert into horseshow.BREED values (269,null,'National Show Horse','Other Pure Gaited',NOW());
insert into horseshow.BREED values (270,null,'National Spotted Saddle Horse','see Spotted Saddle Horse',NOW());
insert into horseshow.BREED values (271,null,'New Forest Pony','Other U.K. Pony (England)',NOW());
insert into horseshow.BREED values (272,null,'Newfoundland pony','North American Pony',NOW());
insert into horseshow.BREED values (273,null,'Nez Perce','Native North American Breeds',NOW());
insert into horseshow.BREED values (274,null,'Nokota','Native North American Breeds',NOW());
insert into horseshow.BREED values (275,null,'Noma','Other Pure/Rare Pony (Japan)',NOW());
insert into horseshow.BREED values (276,null,'Nonius','Other Pure/Rare Horse (Hungary)',NOW());
insert into horseshow.BREED values (277,null,'Nooitgedacht','Other Pure/Rare Pony (South Africa)',NOW());
insert into horseshow.BREED values (278,null,'Nordlandshest (aka Lyngshest)','Other Pure/Rare Pony (Norway)',NOW());
insert into horseshow.BREED values (279,null,'Norfolk Roadster','Other Pure/Rare Horse Breeds',NOW());
insert into horseshow.BREED values (280,null,'Noriker','European draft (Austria)',NOW());
insert into horseshow.BREED values (281,null,'Normandy Cob','French draft',NOW());
insert into horseshow.BREED values (282,null,'North American (Bashkir) Curly Horse','see Bashkir Curly',NOW());
insert into horseshow.BREED values (283,null,'North American Single','Footer',NOW());
insert into horseshow.BREED values (284,null,'North American Spotted Haflinger','North American Ponies',NOW());
insert into horseshow.BREED values (285,null,'North Hester (aka North Swedish Trotter)','Other Pure/Rare Horse Breeds',NOW());
insert into horseshow.BREED values (286,null,'North Swedish Draft','European draft (Sweden)',NOW());
insert into horseshow.BREED values (287,null,'Northlands pony','European Pony (Norway)',NOW());
insert into horseshow.BREED values (288,null,'Norwegian Fjord pony','European Pony (Norway)',NOW());
insert into horseshow.BREED values (289,null,'Novokirghiz','Other Pure/Rare Horse (Kirghistan/Asia)',NOW());
insert into horseshow.BREED values (290,null,'Ob (aka Priob)','Other Pure/Rare Pony (Siberia)',NOW());
insert into horseshow.BREED values (291,null,'Oberlander (aka Noriker)','European draft (Austria)',NOW());
insert into horseshow.BREED values (292,null,'Oldenburg','German Warmblood',NOW());
insert into horseshow.BREED values (293,null,'Onagers','Primitives',NOW());
insert into horseshow.BREED values (294,null,'Orlov Trotter','Harness Racing Breeds (Russia)',NOW());
insert into horseshow.BREED values (295,null,'Pahlavan','Other Pure/Rare Horse Breeds (Iran)',NOW());
insert into horseshow.BREED values (296,null,'Paint','named breed class',NOW());
insert into horseshow.BREED values (297,null,'Palomino','Color Breeds/Other Pure Stock',NOW());
insert into horseshow.BREED values (298,null,'Pampas Horse','Other Pure/Rare Horse (Brazil)',NOW());
insert into horseshow.BREED values (299,null,'Pantaneiro','Other Pure/Rare Horse (Brazil)',NOW());
insert into horseshow.BREED values (300,null,'Paso Fino','named breed class',NOW());
insert into horseshow.BREED values (301,null,'Peneia pony','European Pony (Greece)',NOW());
insert into horseshow.BREED values (302,null,'Peninsula Horse (aka Spanish Anglo','Arab & Hispano',NOW());
insert into horseshow.BREED values (303,null,'Percheron','French draft',NOW());
insert into horseshow.BREED values (304,null,'Persian Arabian','Arabian',NOW());
insert into horseshow.BREED values (305,null,'Peruvian Paso','named breed class',NOW());
insert into horseshow.BREED values (306,null,'Petiso Argentino','Other Pure/Rare Pony (Argentina)',NOW());
insert into horseshow.BREED values (307,null,'Pindos (aka Thessalian)','Other Pure/Rare Pony (Greece)',NOW());
insert into horseshow.BREED values (308,null,'Pintabian','Part Arabian & Arabian Types',NOW());
insert into horseshow.BREED values (309,null,'Pintaloosa','Color Breeds/Other Pure & Mixed Stock',NOW());
insert into horseshow.BREED values (310,null,'Pinto Sporthorse','Other Sport Breeds',NOW());
insert into horseshow.BREED values (311,null,'Pinzgauer (aka Noriker)','European draft (Austria)',NOW());
insert into horseshow.BREED values (312,null,'Pleven','Part Arabian',NOW());
insert into horseshow.BREED values (313,null,'Poitevin (aka Mulassier)','French draft',NOW());
insert into horseshow.BREED values (314,null,'Poney Mousseye','Other Pure/Rare Pony (Cameroon/Africa)',NOW());
insert into horseshow.BREED values (315,null,'Pony of the Americas','North American Pony (U.S.)',NOW());
insert into horseshow.BREED values (316,null,'Posavina','Other Pure/Rare Horse Breeds (Croatia)',NOW());
insert into horseshow.BREED values (317,null,'Pottock pony (aka Basque)','European Pony (Spain/France)',NOW());
insert into horseshow.BREED values (318,null,'PRE (Pura Raza Espanola)','show with Andalusians',NOW());
insert into horseshow.BREED values (319,null,'Priob (aka Ob)','Other Pure/Rare Pony (Siberia)',NOW());
insert into horseshow.BREED values (320,null,'Przewalskis','Primitives',NOW());
insert into horseshow.BREED values (321,null,'Qatgani','Other Pure/Rare Horse (Afghanistan)',NOW());
insert into horseshow.BREED values (322,null,'Quaggas','Primitives',NOW());
insert into horseshow.BREED values (323,null,'Quarab','Mixed Stock Breed',NOW());
insert into horseshow.BREED values (324,null,'Quarter Horse','named breed class',NOW());
insert into horseshow.BREED values (325,null,'Quarter Pony','North American Pony (U.S.)',NOW());
insert into horseshow.BREED values (326,null,'Rheinland Pfalz','Saar',NOW());
insert into horseshow.BREED values (327,null,'Rhenish German Coldblood','European Drafter',NOW());
insert into horseshow.BREED values (328,null,'Rhineland (Draft)','European draft (Germany)',NOW());
insert into horseshow.BREED values (329,null,'Rhinelander','German Warmblood',NOW());
insert into horseshow.BREED values (330,null,'Rocky Mountain Horse','named breed class',NOW());
insert into horseshow.BREED values (331,null,'Romanian Trotter','Other Pure/Rare Horse Breeds (Romania)',NOW());
insert into horseshow.BREED values (332,null,'Rottaler','Other Pure/Rare Horse (Bavaria/Europe)',NOW());
insert into horseshow.BREED values (333,null,'Russian Don','Part Arabian',NOW());
insert into horseshow.BREED values (334,null,'Russian Heavy Draft','Russian draft (Ukraine)',NOW());
insert into horseshow.BREED values (335,null,'Russian Trotter (aka Métis Trotter)','Harness Racing Breeds',NOW());
insert into horseshow.BREED values (336,null,'Sable Island Pony','North American Pony (Canada)',NOW());
insert into horseshow.BREED values (337,null,'Salernitano (aka Salerno)','Other Pure/Rare Horse (Italy)',NOW());
insert into horseshow.BREED values (338,null,'Salerno (aka Salernitano)','Other Pure/Rare Horse (Italy)',NOW());
insert into horseshow.BREED values (339,null,'San Fratello','Other Pure/Rare Horse (Italy)',NOW());
insert into horseshow.BREED values (340,null,'Sandalwood pony','Asian Pony (Indonesia)',NOW());
insert into horseshow.BREED values (341,null,'Sanhi','Other Pure/Rare Horse (China)',NOW());
insert into horseshow.BREED values (342,null,'Sardinian','Other Pure/Rare Horse (Sardinia/Italy)',NOW());
insert into horseshow.BREED values (343,null,'Sardinian pony','European Pony (Italy)',NOW());
insert into horseshow.BREED values (344,null,'Schleswig Heavy Draft','European Draft (Germany)',NOW());
insert into horseshow.BREED values (345,null,'Selle Francais','Other European Warmblood (France)',NOW());
insert into horseshow.BREED values (346,null,'Shackleford Banker Pony','North American Pony (U.S.)',NOW());
insert into horseshow.BREED values (347,null,'Shagya Arab','Arabian',NOW());
insert into horseshow.BREED values (348,null,'Shan pony (aka Burmese)','Asian Pony (Burma)',NOW());
insert into horseshow.BREED values (349,null,'Shetland pony','Other U.K. Pony (Scotland)',NOW());
insert into horseshow.BREED values (350,null,'Shire','British draft',NOW());
insert into horseshow.BREED values (351,null,'Shirazi (aka Darashouri)','Arabian Types',NOW());
insert into horseshow.BREED values (352,null,'Skyros pony','European Pony (Greece)',NOW());
insert into horseshow.BREED values (353,null,'Sokolsky','European Draft (Poland)',NOW());
insert into horseshow.BREED values (354,null,'Sorraia','Other Iberian Breeds (Portugal)',NOW());
insert into horseshow.BREED values (355,null,'Sorraia pony','European Pony (Portugal)',NOW());
insert into horseshow.BREED values (356,null,'Soviet Heavy Draft','Russian draft (Russia)',NOW());
insert into horseshow.BREED values (357,null,'Spanish Anglo','Arab (aka Peninsula Horse & Hispano',NOW());
insert into horseshow.BREED values (358,null,'Spanish Barb','Other Iberian Breeds (Spain)',NOW());
insert into horseshow.BREED values (359,null,'Spanish Jennet','Other Iberian Breeds (Spain)',NOW());
insert into horseshow.BREED values (360,null,'Spanish Mustang','Mustangs',NOW());
insert into horseshow.BREED values (361,null,'Spanish Norman','Other European Warmblood (Spain)',NOW());
insert into horseshow.BREED values (362,null,'Spanish Sulpher Horse','Spanish Types (Spain)',NOW());
insert into horseshow.BREED values (363,null,'Spiti (aka Bhutia) pony','Asian Pony (India)',NOW());
insert into horseshow.BREED values (364,null,'Spotted Saddle Horse','Other Pure Gaited',NOW());
insert into horseshow.BREED values (365,null,'Standardbred','Harness Racing Breeds',NOW());
insert into horseshow.BREED values (366,null,'Suffolk Punch','British draft',NOW());
insert into horseshow.BREED values (367,null,'Sugarbush Drafters','Other Pure Draft',NOW());
insert into horseshow.BREED values (368,null,'Sumba (aka Sumbawa) pony','Asian Pony (Indonesia)',NOW());
insert into horseshow.BREED values (369,null,'Sumbawa (aka Sumba) pony','Asian Pony (Indonesia)',NOW());
insert into horseshow.BREED values (370,null,'Swedish Ardennes','European Draft (Sweden)',NOW());
insert into horseshow.BREED values (371,null,'Swedish Warmblood','Other European Warmblood (Sweden)',NOW());
insert into horseshow.BREED values (372,null,'Swiss Warmblood','Other European Warmblood (Switzerland)',NOW());
insert into horseshow.BREED values (373,null,'Syrian pony','Asian Pony (Syria)',NOW());
insert into horseshow.BREED values (374,null,'Taishuh','Other Pure/Rare Pony (Japan)',NOW());
insert into horseshow.BREED values (375,null,'Tarpans','Primitives',NOW());
insert into horseshow.BREED values (376,null,'Tawleed','Other Pure/Rare Horse (Sudan/Africa)',NOW());
insert into horseshow.BREED values (377,null,'Tchernomor (aka Chernomor)','Other Pure/Rare Horse (Caucasus Mnts/Russia)',NOW());
insert into horseshow.BREED values (378,null,'Tennessee Walking Horse','named breed class',NOW());
insert into horseshow.BREED values (379,null,'Tennuvian','Other Pure Gaited',NOW());
insert into horseshow.BREED values (380,null,'Tersk','Arabian',NOW());
insert into horseshow.BREED values (381,null,'Thessalian (aka Pindos)','Other Pure/Rare Pony (Greece)',NOW());
insert into horseshow.BREED values (382,null,'Thoroughbred','named breed class',NOW());
insert into horseshow.BREED values (383,null,'Tibetan pony','Asian Pony (China)',NOW());
insert into horseshow.BREED values (384,null,'Tiger Horse','Other Pure/Rare Horse (Spain)',NOW());
insert into horseshow.BREED values (385,null,'Timor (aka Flores)','Other Pure/Rare Pony (Indonesia/Asia)',NOW());
insert into horseshow.BREED values (386,null,'Timor pony','Asian Pony (Indonesia)',NOW());
insert into horseshow.BREED values (387,null,'Tinker Horse (aka Irish Tinker Horse)','Carriage & Driving (Ireland)',NOW());
insert into horseshow.BREED values (388,null,'Tokara','Other Pure/Rare Pony (Japan)',NOW());
insert into horseshow.BREED values (389,null,'Tori','Other Pure/Rare Horse (Estonia/Europe)',NOW());
insert into horseshow.BREED values (390,null,'Toric','European & Russian draft (Estonia)',NOW());
insert into horseshow.BREED values (391,null,'Torijski (aka Klepper)','Other Pure Draft Breeds',NOW());
insert into horseshow.BREED values (392,null,'Trait du Nord','French draft',NOW());
insert into horseshow.BREED values (393,null,'Trakehner','German Warmblood',NOW());
insert into horseshow.BREED values (394,null,'Tuigpaard (aka Dutch Harness Horse)','Carriage & Driving breeds',NOW());
insert into horseshow.BREED values (395,null,'Turkoman','Other Pure/Rare Horse (Turkmenistan/Asia)',NOW());
insert into horseshow.BREED values (396,null,'Ukranian Riding Horse','Other European Warmblood (Ukraine)',NOW());
insert into horseshow.BREED values (397,null,'Unmol','Other Pure/Rare Horse (Punjab states/India)',NOW());
insert into horseshow.BREED values (398,null,'Uzunyayla','Other Pure/Rare Horse (Turkey)',NOW());
insert into horseshow.BREED values (399,null,'Ventasso','Other Pure/Rare Horse (Italy)',NOW());
insert into horseshow.BREED values (400,null,'Viatka pony','European Pony (Russia)',NOW());
insert into horseshow.BREED values (401,null,'Virginia Highlander','Native North American Breeds',NOW());
insert into horseshow.BREED values (402,null,'Vlaamperd','Other Pure/Rare Horse (South Africa)',NOW());
insert into horseshow.BREED values (403,null,'Vladimir Heavy Draft','Russian draft',NOW());
insert into horseshow.BREED values (404,null,'Waler','see Australian Waler',NOW());
insert into horseshow.BREED values (405,null,'Walkaloosa','Mixed Gaited Breeds',NOW());
insert into horseshow.BREED values (406,null,'Warlander','Fresian cross **',NOW());
insert into horseshow.BREED values (407,null,'Welara pony','North American Pony (U.S.)',NOW());
insert into horseshow.BREED values (408,null,'Westphalian','German Warmblood',NOW());
insert into horseshow.BREED values (409,null,'Wielkopolski','Other European Warmblood (Poland)',NOW());
insert into horseshow.BREED values (410,null,'Wurttemberg','German Warmblood',NOW());
insert into horseshow.BREED values (411,null,'Xilingol','Other Pure/Rare Horse (Mongolia/Asia)',NOW());
insert into horseshow.BREED values (412,null,'Yakut','Other Pure/Rare Pony (Siberia)',NOW());
insert into horseshow.BREED values (413,null,'Yangi','Other Pure/Rare Pony (China)',NOW());
insert into horseshow.BREED values (414,null,'Yili','Other Pure/Rare Horse (China)',NOW());
insert into horseshow.BREED values (415,null,'Yonaguni','Other Pure/Rare Pony (Japan)',NOW());
insert into horseshow.BREED values (416,null,'Zangersheide','Other European Warmblood (Belgium)',NOW());
insert into horseshow.BREED values (417,null,'Zaniskari','Other Pure/Rare Pony (India)',NOW());
insert into horseshow.BREED values (418,null,'Zapatero','Other Iberian Breeds (Spain)',NOW());
insert into horseshow.BREED values (419,null,'Zemaituka pony','European Pony (Lithuania)',NOW());
insert into horseshow.BREED values (420,null,'Zhemaichu (aka Zhumdka)','Other Pure/Rare Horse (Lithuania)',NOW());
insert into horseshow.BREED values (421,null,'Zhumdka (aka Zhemaichu)','Other Pure/Rare Horse (Lithuania)',NOW());
insert into horseshow.BREED values (422,null,'Zweibrücker','German Warmblood',NOW());
