insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (1,   1, 3, null, 'ORIGINAL FINISH REGULAR RUN DIVISION', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (2,   1, 2, 1, 'Draft Breed & Type Section', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (101, 1, 1, 2, 'British Breeds', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (102, 1, 1, 2, 'Other United Kingdom Breeds', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (103, 1, 1, 2, 'French Breeds', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (104, 1, 1, 2, 'European & Russian Breeds', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (105, 1, 1, 2, 'Other Pure and Mixed Draft Breeds', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (106, 1, 1, 2, 'Donkeys and Mules; Zebras, Primitive Breeds', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (3,   1, 2, 1, 'Pony Breed & Type Section', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (107, 1, 1, 3, 'Welsh Ponies & Cobs (all sections)', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (108, 1, 1, 3, 'Other United Kingdom Breeds', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (109, 1, 1, 3, 'European, Australian, African & Asian Breeds', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (110, 1, 1, 3, 'North & South American Breeds', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (111, 1, 1, 3, 'Miniature Horse/Pony, Other Pure and Mixed Pony Breeds', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (4,   1, 2, 1, 'Stock Breed & Type Section', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (112, 1, 1, 4, 'Quarter Horse Stallions & Geldings', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (113, 1, 1, 4, 'Quarter Horse Mares', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (114, 1, 1, 4, 'Appaloosa Stallions & Geldings', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (115, 1, 1, 4, 'Appaloosa Mares', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (116, 1, 1, 4, 'Paint Stallions & Geldings', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (117, 1, 1, 4, 'Paint Mares', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (118, 1, 1, 4, 'Color “Breeds”, Other Pure and Mixed Breeds', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (5,   1, 2, 1, 'Light & Gaited Breed  & Type Section', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (119, 1, 1, 5, 'Arabian Stallions & Geldings', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (120, 1, 1, 5, 'Arabian Mares', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (121, 1, 1, 5, 'Part Arabian and Arabian Types', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (122, 1, 1, 5, 'Morgan', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (123, 1, 1, 5, 'T.W.H., M.F.T., & R.M.H.', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (124, 1, 1, 5, 'American Saddlebred ', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (125, 1, 1, 5, 'Other Pure and Mixed Breeds', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (6,   1, 2, 1, 'Sport Breed & Type Section', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (126, 1, 1, 6, 'Thoroughbred Stallions ', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (127, 1, 1, 6, 'Thoroughbred Mares &Geldings', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (128, 1, 1, 6, 'German Warmbloods', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (129, 1, 1, 6, 'Other European Warmbloods', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (130, 1, 1, 6, 'Carriage/Driving, Harness Racing Breeds ', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (131, 1, 1, 6, 'Other Pure & Mixed Sport & Racing Breeds', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (7,   1, 2, 1, 'Spanish, North American & Other Breed & Type Section', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (132, 1, 1, 7, 'Andalusian & Luisitano', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (133, 1, 1, 7, 'Paso Fino & Peruvian Paso', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (134, 1, 1, 7, 'Other Iberian Breeds, Mixed Spanish Breeds & Spanish Types', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (135, 1, 1, 7, 'Native North American Breeds', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (136, 1, 1, 7, 'Mustangs, all types/origins', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (137, 1, 1, 7, 'ALL Other Pure Breeds, ALL Cross-Type Mixed Breeds, Rare/Unusual Breeds	', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (8,   1, 3, null, 'ORIGINAL FINISH SPECIAL RUN DIVISION', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (9,   1, 2, 8, 'Draft Breed & Type Section', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (201, 1, 1, 9, 'British Breeds', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (202, 1, 1, 9, 'Other United Kingdom Breeds', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (203, 1, 1, 9, 'French Breeds', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (204, 1, 1, 9, 'European & Russian Breeds', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (205, 1, 1, 9, 'Other Pure and Mixed Draft Breeds', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (206, 1, 1, 9, 'Donkeys and Mules; Zebras, Primitive Breeds', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (10,  1, 2, 8, 'Pony Breed & Type Section', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (207, 1, 1, 10, 'Welsh Ponies & Cobs (all sections)', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (208, 1, 1, 10, 'Other United Kingdom Breeds', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (209, 1, 1, 10, 'European, Australian, African & Asian Breeds', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (210, 1, 1, 10, 'North & South American Breeds', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (211, 1, 1, 10, 'Miniature Horse/Pony, Other Pure and Mixed Pony Breeds', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (11,  1, 2, 8, 'Stock Breed & Type Section', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (212, 1, 1, 11, 'Quarter Horse Stallions & Geldings', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (213, 1, 1, 11, 'Quarter Horse Mares', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (214, 1, 1, 11, 'Appaloosa Stallions & Geldings', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (215, 1, 1, 11, 'Appaloosa Mares', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (216, 1, 1, 11, 'Paint Stallions & Geldings', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (217, 1, 1, 11, 'Paint Mares', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (218, 1, 1, 11, 'Color “Breeds”, Other Pure and Mixed Breeds', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (12,  1, 2, 8, 'Light & Gaited Breed  & Type Section', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (219, 1, 1, 12, 'Arabian Stallions & Geldings', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (220, 1, 1, 12, 'Arabian Mares', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (221, 1, 1, 12, 'Part Arabian and Arabian Types', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (222, 1, 1, 12, 'Morgan', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (223, 1, 1, 12, 'T.W.H., M.F.T., & R.M.H.', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (224, 1, 1, 12, 'American Saddlebred ', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (225, 1, 1, 12, 'Other Pure and Mixed Breeds', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (13, 1, 2, 8, 'Sport Breed & Type Section', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (226, 1, 1, 13, 'Thoroughbred Stallions ', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (227, 1, 1, 13, 'Thoroughbred Mares &Geldings', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (228, 1, 1, 13, 'German Warmbloods', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (229, 1, 1, 13, 'Other European Warmbloods', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (230, 1, 1, 13, 'Carriage/Driving, Harness Racing Breeds ', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (231, 1, 1, 13, 'Other Pure & Mixed Sport & Racing Breeds', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (14, 1, 2, 8, 'Spanish, North American & Other Breed & Type Section', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (232, 1, 1, 14, 'Andalusian & Luisitano', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (233, 1, 1, 14, 'Paso Fino & Peruvian Paso', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (234, 1, 1, 14, 'Other Iberian Breeds, Mixed Spanish Breeds & Spanish Types', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (235, 1, 1, 14, 'Native North American Breeds', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (236, 1, 1, 14, 'Mustangs, all types/origins', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (237, 1, 1, 14, 'ALL Other Pure Breeds, ALL Cross-Type Mixed Breeds, Rare/Unusual Breeds', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (15, 1, 3, null, 'COLLECTIBILITY DIVISION', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (16, 1, 2, 15, 'Miscellaneous Section', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (301, 1, 1, 16, 'Bulls, regular runs', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (302, 1, 1, 16, 'Bulls, special & limited runs', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (303, 1, 1, 16, 'Cows and Calves', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (304, 1, 1, 16, 'Dogs ', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (305, 1, 1, 16, 'Other Realistic Animals', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (306, 1, 1, 16, 'Fantasy', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (307, 1, 1, 16, 'Clocks and Lamps', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (308, 1, 1, 16, 'Horses with original plastic riders and/or tack', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (309, 1, 1, 16, 'Horses attached to bases or produced with other accessories & Flocked models', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (310, 1, 1, 16, 'Models with original stickers', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (311, 1, 1, 16, 'Vintage models in original package', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (17, 1, 2, 15, 'Unrealistic Color Section', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (312, 1, 1, 17, 'Wood grains - standing adults ', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (313, 1, 1, 17, 'Wood grains - action adults', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (314, 1, 1, 17, 'Wedgewood & Copenhagen - Vintage', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (315, 1, 1, 17, 'Wedgewood & Copenhagen - Modern', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (316, 1, 1, 17, 'Gold Charm & Florentine - Vintage', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (317, 1, 1, 17, 'Gold Charm & Florentine – Modern', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (318, 1, 1, 17, 'Silver & Silver Filigree', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (319, 1, 1, 17, 'Models with an unrealistic design ', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (320, 1, 1, 17, 'Chalkies & Pearlies - standing adults', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (321, 1, 1, 17, 'Chalkies & Pearlies - action adults', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (322, 1, 1, 17, 'Charcoals & Smoke', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (323, 1, 1, 17, 'Red Roan', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (324, 1, 1, 17, 'Other Unrealistic Color Equine', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (325, 1, 1, 17, 'Unrealistic Color Non-Equine/Fantasy', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (18, 1, 2, 15, 'Limited Run Section', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (326, 1, 1, 18, 'Unrealistic Color or Fantasy', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (327, 1, 1, 18, 'Light Breeds', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (328, 1, 1, 18, 'Gaited Breeds', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (329, 1, 1, 18, 'Stock Breeds', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (330, 1, 1, 18, 'Spanish Breeds', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (331, 1, 1, 18, 'TB/Racing Breeds', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (332, 1, 1, 18, 'WB/Carriage Breeds', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (333, 1, 1, 18, 'Draft Breeds & Pony Breeds', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (334, 1, 1, 18, 'Other Breeds & Mixed Breeds', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (335, 1, 1, 18, 'Connoisseur Light/Gaited Breeds', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (336, 1, 1, 18, 'Connoisseur Stock/Spanish Breeds ', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (337, 1, 1, 18, 'Connoisseur TB/WB/Racing/Carriage Breeds', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (338, 1, 1, 18, 'Connoisseur Draft/Pony/Other/Mixed/Unrealistic', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (339, 1, 1, 18, 'OOAK/Test Light/Gaited Breeds', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (340, 1, 1, 18, 'OOAK/Test Stock/Spanish Breeds', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (341, 1, 1, 18, 'OOAK/Test TB/WB/Racing/Carriage Breeds', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (342, 1, 1, 18, 'OOAK/Test Draft/Pony/Other/Mixed/Unrealistic', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (19, 1, 2, 15, 'Porcelains, Factory Resins, Metals Section (ALL)', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (343, 1, 1, 19, 'Light & Gaited Breeds', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (344, 1, 1, 19, 'Stock & Spanish Breeds', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (345, 1, 1, 19, 'Sport & Draft Breeds', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (346, 1, 1, 19, 'Pony & Other/Mixed Breeds', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (20, 1, 3, null, 'CUSTOMIZED DIVISION', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (21, 1, 2, 20, 'Draft Breed & Type Section', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (400, 1, 1, 21, 'Custom Glazed Porcelains', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (401, 1, 1, 21, 'United Kingdom & French Breeds', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (402, 1, 1, 21, 'European, Russian, and Other Pure/Mixed Breeds', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (403, 1, 1, 21, 'Donkeys, Mules, Zebras, Primitives & Non-Equids', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (22, 1, 2, 20, 'Pony Breed & Type Section', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (404, 1, 1, 22, 'United Kingdom Breeds', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (405, 1, 1, 22, 'European, Asian, African, Australian Breeds', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (406, 1, 1, 22, 'American Breeds', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (407, 1, 1, 22, 'Miniature Horses, & Other Pure/Mixed', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (23, 1, 2, 20, 'Stock Breed & Type Section', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (408, 1, 1, 23, 'Quarter Horse ', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (409, 1, 1, 23, 'Appaloosa', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (410, 1, 1, 23, 'Paint', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (411, 1, 1, 23, 'North American & Color Breeds, Other Pure/Mixed', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (24, 1, 2, 20, 'Light & Gaited Breed & Type Section', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (412, 1, 1, 24, 'Arabian ', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (413, 1, 1, 24, 'Part-Arabian & Arabian Types', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (414, 1, 1, 24, 'TWH, MFT, RMH, ASB ', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (415, 1, 1, 24, 'Morgan & Other Pure/Mixed ', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (25, 1, 2, 20, 'Sport Breed & Type Section', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (416, 1, 1, 25, 'Thoroughbred ', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (417, 1, 1, 25, 'Warmbloods', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (418, 1, 1, 25, 'Carriage & Driving Breeds', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (419, 1, 1, 25, 'Harness Racing Breeds, Other Pure/Mixed', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (26, 1, 2, 20, 'Spanish & Other Breed & Type Section', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (420, 1, 1, 26, 'Andalusian, Luisitaino, Paso Fino, Per. Paso ', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (421, 1, 1, 26, 'Mustangs, all types and origins', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (422, 1, 1, 26, 'Other Iberian Breeds and Other Pure/Mixed', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (423, 1, 1, 26, 'All Other Pure/Rare Breeds & Mixed Breeds', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (27, 1, 2, 20, 'Miscellaneous Section', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (424, 1, 1, 27, 'Fantasy animal', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (425, 1, 1, 27, 'Unrealistic Color (non-fantasy)', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (426, 1, 1, 27, 'Dogs, Cats, Cattle, & Other Animals, all scales', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (427, 1, 1, 27, 'Unrealistic Color or Fantasy Minis (including foals)', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (28, 1, 2, 20, 'Customized by Amateur Owner Section - all scales', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (428, 1, 1, 28, 'Draft Breeds/Types			', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (429, 1, 1, 28, 'Pony Breeds /Types				', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (430, 1, 1, 28, 'Stock, Spanish & Other Breeds/Types		', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (431, 1, 1, 28, 'Light & Gaited Breeds/Types', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (432, 1, 1, 28, 'Sport & Carriage Breeds/Types', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (433, 1, 1, 28, 'Longears, Zebra, Other Types', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (434, 1, 1, 28, 'Foals, all breeds', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (29, 1, 3, null, 'FOAL DIVISION', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (30, 1, 2, 29, 'Regular Run OF Section', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (501, 1, 1, 30, 'Draft Breeds & Types', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (502, 1, 1, 30, 'Pony Breeds & Types', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (503, 1, 1, 30, 'Stock Breeds & Types', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (504, 1, 1, 30, 'Light & Gaited Breeds & Types', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (505, 1, 1, 30, 'Sport Breeds & Types', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (506, 1, 1, 30, 'Spanish & Other Breeds & Types', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (31, 1, 2, 29, 'Special Run OF Section', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (507, 1, 1, 31, 'Draft Breeds & Types', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (508, 1, 1, 31, 'Pony Breeds & Types', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (509, 1, 1, 31, 'Stock Breeds & Types', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (510, 1, 1, 31, 'Light & Gaited Breeds & Types', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (511, 1, 1, 31, 'Sport Breeds & Types', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (512, 1, 1, 31, 'Spanish & Other Breeds & Types ', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (32, 1, 2, 29, 'Collectibility OF Section (includes SM’s)', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (513, 1, 1, 32, 'Woodgrain, Red Roan', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (514, 1, 1, 32, 'Wedgewood/Copenhagen, Gold Charm/Florentine', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (515, 1, 1, 32, 'Limited Run (except OOAK’s)', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (516, 1, 1, 32, 'Chalkies & Pearlies', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (517, 1, 1, 32, 'Charcoal & Smoke (incl. glossy)', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (518, 1, 1, 32, 'Other Collectible, incl. Keychains', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (33, 1, 2, 29, 'Customized Section (includes SM’s)', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (519, 1, 1, 33, 'Draft Breeds & Types', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (520, 1, 1, 33, 'Pony Breeds & Types', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (521, 1, 1, 33, 'Stock Breeds & Types', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (522, 1, 1, 33, 'Light & Gaited Breeds & Types', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (523, 1, 1, 33, 'Sport Breeds & Types', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (524, 1, 1, 33, 'Spanish & Other Breeds & Types', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (34, 1, 2, 29, 'O.F. Mini Section (RR & SR)', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (525, 1, 1, 34, 'Draft Breeds & Types', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (526, 1, 1, 34, 'Pony Breeds & Types', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (527, 1, 1, 34, 'Stock Breeds & Types', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (528, 1, 1, 34, 'Light & Gaited Breeds & Types', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (529, 1, 1, 34, 'Sport Breeds & Types', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (530, 1, 1, 34, 'Spanish & Other Breeds & Types', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (35, 1, 3, null, 'MINI DIVISION', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (36, 1, 2, 35, 'Original Finish Section (RR & SR)', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (601, 1, 1, 36, 'Draft Breeds', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (602, 1, 1, 36, 'Pony Breeds', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (603, 1, 1, 36, 'Arabian & Part Arabian', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (604, 1, 1, 36, 'Morgan & Gaited', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (605, 1, 1, 36, 'Spanish & Mustangs (all)', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (606, 1, 1, 36, 'Longears, & Other Pure & Mixed', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (607, 1, 1, 36, 'Quarter Horse', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (608, 1, 1, 36, 'Appaloosa', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (609, 1, 1, 36, 'Paint', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (610, 1, 1, 36, 'Thoroughbred/Racing Breeds', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (611, 1, 1, 36, 'Warmblood/Carriage Breeds', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (612, 1, 1, 36, 'Other Pure & Mixed, & Rare Breeds', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (37, 1, 2, 35, 'Customized Section', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (613, 1, 1, 37, 'Draft Breeds & Types', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (614, 1, 1, 37, 'Pony Breeds & Types', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (615, 1, 1, 37, 'Stock Breeds & Types', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (616, 1, 1, 37, 'Sport/Carriage Breeds & Types', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (617, 1, 1, 37, 'Light Breeds & Types', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (618, 1, 1, 37, 'Gaited Breeds & Types ', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (619, 1, 1, 37, 'Spanish Breeds & Types', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (620, 1, 1, 37, 'Other Pure/Mixed & Mustangs (all)', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (38, 1, 2, 35, 'Collectibility', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (621, 1, 1, 38, ' Keychains', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (622, 1, 1, 38, ' Copenhagen/Gold Charm/Florentine/Wedgewood', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (623, 1, 1, 38, ' Unrealistic Designs', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (624, 1, 1, 38, ' Unpainted, Metallic, Unrealistic Glossy', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (625, 1, 1, 38, ' Other Collectible (incl. Flockies, no ornaments) ', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (626, 1, 1, 38, ' Non-Equine/Fantasy', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (39, 1, 3, null, 'NOVICE PERFORMANCE DIVISION', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (48, 1, 2, 39, 'NOVICE PERFORMANCE SECTION', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (801, 1, 1, 48, 'Harness / Other Performance', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (802, 1, 1, 48, 'Costume / Parade', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (803, 1, 1, 48, 'Western Trail', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (804, 1, 1, 48, 'Western Stock Work/Gymkhana/Other Western', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (805, 1, 1, 48, 'Western Pleasure', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (806, 1, 1, 48, 'Hunter Over Fences / Jumper / Cross Country', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (807, 1, 1, 48, 'English Trail/Gymkhana/Other English', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (808, 1, 1, 48, 'Huntseat Pleasure', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (40, 1, 3, null, 'OPEN O.F. PERFORMANCE DIVISION', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (41, 1, 2, 40, 'Miscellaneous Performance Section', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (701, 1, 1, 41, 'Harness Events ', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (702, 1, 1, 41, 'Pleasure, Fine, or Draft Harness', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (703, 1, 1, 41, 'Park / Saddleseat', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (704, 1, 1, 41, 'Indian Costume', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (705, 1, 1, 41, 'Arabian Costume', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (706, 1, 1, 41, 'Parade  ', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (707, 1, 1, 41, 'Other Costume', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (708, 1, 1, 41, 'Other Performance			', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (709, 1, 1, 41, 'Scene', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (710, 1, 1, 41, 'Showmanship', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (42, 1, 2, 40, 'Huntseat Performance Section', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (711, 1, 1, 42, 'Jumper/Cross Country/Eventing', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (712, 1, 1, 42, 'Other English, including Gymkahna', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (713, 1, 1, 42, 'English Trail', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (714, 1, 1, 42, 'Hunter Over Fences', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (715, 1, 1, 42, 'Huntseat Pleasure', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (716, 1, 1, 42, 'Dressage', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (43, 1, 2, 40, 'Western Performance Section', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (717, 1, 1, 43, 'Roping', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (718, 1, 1, 43, 'Cutting & Other Stock Work', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (719, 1, 1, 43, 'Western Games', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (720, 1, 1, 43, 'Other Western, including Patternwork', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (721, 1, 1, 43, 'Western Trail', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (722, 1, 1, 43, 'Western Pleasure', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (44, 1, 3, null, 'OPEN CM PERFORMANCE DIVISION', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (45, 1, 2, 44, 'Huntseat Performance Section', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (901, 1, 1, 45, 'Jumper/Cross Country/Eventing', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (902, 1, 1, 45, 'Other English, including Gymkahna', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (903, 1, 1, 45, 'English Trail', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (904, 1, 1, 45, 'Hunter Over Fences', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (905, 1, 1, 45, 'Huntseat Pleasure', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (906, 1, 1, 45, 'Dressage', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (46, 1, 2, 44, 'Western Performance Section', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (907, 1, 1, 46, 'Roping', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (908, 1, 1, 46, 'Cutting & Other Stock Work', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (909, 1, 1, 46, 'Western Games', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (910, 1, 1, 46, 'Other Western, including Patternwork', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (911, 1, 1, 46, 'Western Trail', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (912, 1, 1, 46, 'Western Pleasure', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (47, 1, 2, 44, 'Miscellaneous Performance Section', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (913, 1, 1, 47, 'Harness Events ', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (914, 1, 1, 47, 'Pleasure, Fine, or Draft Harness', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (915, 1, 1, 47, 'Park / Saddleseat', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (916, 1, 1, 47, 'Indian Costume', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (917, 1, 1, 47, 'Arabian Costume', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (918, 1, 1, 47, 'Parade  ', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (919, 1, 1, 47, 'Other Costume', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (920, 1, 1, 47, 'Other Performance			', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (921, 1, 1, 47, 'Scene', NOW());
insert into frithi_HORSESHOW.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (922, 1, 1, 47, 'Showmanship', NOW());

insert into DIVISION values (0,1,4,327,'A. Light Breeds/Breed', null, NOW(), NOW());
insert into DIVISION values (0,1,4,327,'B. Light Breeds/Collectibility', null, NOW(), NOW());

insert into DIVISION values (0,1,4,328,'A. Gaited Breeds/Breed', null, NOW(), NOW());
insert into DIVISION values (0,1,4,328,'B. Gaited Breeds/Collectibility', null, NOW(), NOW());

insert into DIVISION values (0,1,4,329,'A. Stock Breeds/Breed', null, NOW(), NOW());
insert into DIVISION values (0,1,4,329,'B. Stock Breeds/Collectibility', null, NOW(), NOW());

insert into DIVISION values (0,1,4,330,'A. Spanish Breeds/Breed', null, NOW(), NOW());
insert into DIVISION values (0,1,4,330,'B. Spanish Breeds/Collectibility', null, NOW(), NOW());

insert into DIVISION values (0,1,4,331,'A. TB/Racing Breeds/Breed', null, NOW(), NOW());
insert into DIVISION values (0,1,4,331,'B. TB/Racing Breeds /Collectibility', null, NOW(), NOW());

insert into DIVISION values (0,1,4,332,'A. WB/Carriage Breeds/Breed', null, NOW(), NOW());
insert into DIVISION values (0,1,4,332,'B. WB/Carriage Breeds/Collectibility', null, NOW(), NOW());

insert into DIVISION values (0,1,4,333,'A. Draft Breeds & Pony Breeds/Breed', null, NOW(), NOW());
insert into DIVISION values (0,1,4,333,'B. Draft Breeds & Pony Breeds/Collectibility', null, NOW(), NOW());

insert into DIVISION values (0,1,4,334,'A. Other Breeds & Mixed Breeds/Breed', null, NOW(), NOW());
insert into DIVISION values (0,1,4,334,'B. Other Breeds & Mixed Breeds/Collectibility', null, NOW(), NOW());

insert into DIVISION values (0,1,4,335,'A. Connoisseur Light/Gaited Breeds/Breed', null, NOW(), NOW());
insert into DIVISION values (0,1,4,335,'B. Connoisseur Light/Gaited Breeds/Collectibility', null, NOW(), NOW());

insert into DIVISION values (0,1,4,336,'A. Connoisseur Stock/Spanish Breeds/Breed', null, NOW(), NOW());
insert into DIVISION values (0,1,4,336,'B. Connoisseur Stock/Spanish Breeds/Collectibility', null, NOW(), NOW());

insert into DIVISION values (0,1,4,337,'A. Connoisseur TB/WB/Racing/Carriage Breeds/Breed', null, NOW(), NOW());
insert into DIVISION values (0,1,4,337,'B. Connoisseur TB/WB/Racing/Carriage Breeds/Collectibility', null, NOW(), NOW());

insert into DIVISION values (0,1,4,338,'A. Connoisseur Draft/Pony/Other/Mixed/Unrealistic/Breed', null, NOW(), NOW());
insert into DIVISION values (0,1,4,338,'B. Connoisseur Draft/Pony/Other/Mixed/Unrealistic/Collectibility', null, NOW(), NOW());

insert into DIVISION values (0,1,4,339,'A. OOAK/Test Light/Gaited Breeds/Breed', null, NOW(), NOW());
insert into DIVISION values (0,1,4,339,'B. OOAK/Test Light/Gaited Breeds/Collectibility', null, NOW(), NOW());

insert into DIVISION values (0,1,4,340,'A. OOAK/Test Stock/Spanish Breeds/Breed', null, NOW(), NOW());
insert into DIVISION values (0,1,4,340,'B. OOAK/Test Stock/Spanish Breeds/Collectibility', null, NOW(), NOW());

insert into DIVISION values (0,1,4,341,'A. OOAK/Test TB/WB/Racing/Carriage Breeds/Breed', null, NOW(), NOW());
insert into DIVISION values (0,1,4,341,'B. OOAK/Test TB/WB/Racing/Carriage Breeds/Collectibility', null, NOW(), NOW());

insert into DIVISION values (0,1,4,342,'A. OOAK/Test Draft/Pony/Other/Mixed/Unrealistic/Breed', null, NOW(), NOW());
insert into DIVISION values (0,1,4,342,'B. OOAK/Test Draft/Pony/Other/Mixed/Unrealistic/Collectibility', null, NOW(), NOW());

insert into DIVISION values (0,1,4,343,'A. Light & Gaited Breeds/Breed', null, NOW(), NOW());
insert into DIVISION values (0,1,4,343,'B. Light & Gaited Breeds/Collectibility', null, NOW(), NOW());

insert into DIVISION values (0,1,4,344,'A. Stock & Spanish Breeds/Breed', null, NOW(), NOW());
insert into DIVISION values (0,1,4,344,'B. Stock & Spanish Breeds/Collectibility', null, NOW(), NOW());

insert into DIVISION values (0,1,4,345,'A. Sport & Draft Breeds/Breed', null, NOW(), NOW());
insert into DIVISION values (0,1,4,345,'B. Sport & Draft Breeds/Collectibility', null, NOW(), NOW());

insert into DIVISION values (0,1,4,346,'A. Pony & Other/Mixed Breeds/Breed', null, NOW(), NOW());
insert into DIVISION values (0,1,4,346,'B. Pony & Other/Mixed Breeds/Collectibility', null, NOW(), NOW());

