insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (1,2,3,null, 'ORIGINAL FINISH REGULAR RUN DIVISION', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (12,2,2,1, 'Draft Breed & Type Section', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (101,2,1,12, 'British Breeds', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (102,2,1,12, 'Other United Kingdom Breeds', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (103,2,1,12, 'French Breeds', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (104,2,1,12, 'European & Russian Breeds', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (105,2,1,12, 'Other Pure and Mixed Draft Breeds', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (106,2,1,12, 'Donkeys and Mules; Zebras, Primitive Breeds', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (13,2,2,1, 'Pony Breed & Type Section', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (107,2,1,13, 'Welsh Ponies & Cobs (all sections)', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (108,2,1,13, 'Other United Kingdom Breeds', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (109,2,1,13, 'European, Australian, African & Asian Breeds', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (110,2,1,13, 'North & South American Breeds', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (111,2,1,13, 'Miniature Horse/Pony, Other Pure and Mixed Pony Breeds', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (14,2,2,1, 'Stock Breed & Type Section', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (112,2,1,14, 'Quarter Horse Stallions & Geldings', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (113,2,1,14, 'Quarter Horse Mares', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (114,2,1,14, 'Appaloosa Stallions & Geldings', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (115,2,1,14, 'Appaloosa Mares', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (116,2,1,14, 'Paint Stallions & Geldings', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (117,2,1,14, 'Paint Mares', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (118,2,1,14, 'Color Breeds, Other Pure and Mixed Breeds', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (15,2,2,1, 'Light & Gaited Breed  & Type Section', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (119,2,1,15, 'Arabian Stallions & Geldings', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (120,2,1,15, 'Arabian Mares', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (121,2,1,15, 'Part Arabian and Arabian Types', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (122,2,1,15, 'Morgan', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (123,2,1,15, 'T.W.H., M.F.T., & R.M.H.', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (124,2,1,15, 'American Saddlebred', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (125,2,1,15, 'Other Pure and Mixed Breeds', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (16,2,2,1, 'Sport Breed & Type Section', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (126,2,1,16, 'Thoroughbred Stallions', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (127,2,1,16, 'Thoroughbred Mares &Geldings', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (128,2,1,16, 'German Warmbloods', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (129,2,1,16, 'Other European Warmbloods', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (130,2,1,16, 'Carriage/Driving, Harness Racing Breeds', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (131,2,1,16, 'Other Pure & Mixed Sport & Racing Breeds', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (17,2,2,1, 'Spanish, North American & Other Breed & Type Section', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (132,2,1,17, 'Andalusian & Luisitano', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (133,2,1,17, 'Paso Fino & Peruvian Paso', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (134,2,1,17, 'Other Iberian Breeds, Mixed Spanish Breeds & Spanish Types', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (135,2,1,17, 'Native North American Breeds', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (136,2,1,17, 'Mustangs, all types/origins', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (137,2,1,17, 'ALL Other Pure Breeds, ALL Cross-Type Mixed Breeds, Rare/Unusual Breeds', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (2,2,3,null, 'ORIGINAL FINISH SPECIAL RUN DIVISION', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (18,2,2,2, 'Draft Breed & Type Section', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (201,2,1,18, 'British Breeds', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (202,2,1,18, 'Other United Kingdom Breeds', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (203,2,1,18, 'French Breeds', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (204,2,1,18, 'European & Russian Breeds', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (205,2,1,18, 'Other Pure and Mixed Draft Breeds', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (206,2,1,18, 'Donkeys and Mules; Zebras, Primitive Breeds', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (19,2,2,2, 'Pony Breed & Type Section', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (207,2,1,19, 'Welsh Ponies & Cobs (all sections)', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (208,2,1,19, 'Other United Kingdom Breeds', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (209,2,1,19, 'European, Australian, African & Asian Breeds', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (210,2,1,19, 'North & South American Breeds', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (211,2,1,19, 'Miniature Horse/Pony, Other Pure and Mixed Pony Breeds', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (20,2,2,2, 'Stock Breed & Type Section', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (212,2,1,20, 'Quarter Horse Stallions & Geldings', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (213,2,1,20, 'Quarter Horse Mares', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (214,2,1,20, 'Appaloosa Stallions & Geldings', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (215,2,1,20, 'Appaloosa Mares', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (216,2,1,20, 'Paint Stallions & Geldings', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (217,2,1,20, 'Paint Mares', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (218,2,1,20, 'Color Breeds, Other Pure and Mixed Breeds', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (21,2,2,2, 'Light & Gaited Breed  & Type Section', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (219,2,1,21, 'Arabian Stallions & Geldings', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (220,2,1,21, 'Arabian Mares', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (221,2,1,21, 'Part Arabian and Arabian Types', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (222,2,1,21, 'Morgan', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (223,2,1,21, 'T.W.H., M.F.T., & R.M.H.', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (224,2,1,21, 'American Saddlebred', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (225,2,1,21, 'Other Pure and Mixed Breeds', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (22,2,2,2, 'Sport Breed & Type Section', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (226,2,1,22, 'Thoroughbred Stallions', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (227,2,1,22, 'Thoroughbred Mares &Geldings', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (228,2,1,22, 'German Warmbloods', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (229,2,1,22, 'Other European Warmbloods', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (230,2,1,22, 'Carriage/Driving, Harness Racing Breeds', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (231,2,1,22, 'Other Pure & Mixed Sport & Racing Breeds', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (23,2,2,2, 'Spanish, North American & Other Breed & Type Section', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (232,2,1,23, 'Andalusian & Luisitano', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (233,2,1,23, 'Paso Fino & Peruvian Paso', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (234,2,1,23, 'Other Iberian Breeds, Mixed Spanish Breeds & Spanish Types', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (235,2,1,23, 'Native North American Breeds', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (236,2,1,23, 'Mustangs, all types/origins', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (237,2,1,23, 'ALL Other Pure Breeds, ALL Cross-Type Mixed Breeds, Rare/Unusual Breeds', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (3,2,3,null, 'COLLECTIBILITY DIVISION', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (24,2,2,3, 'Miscellaneous Section', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (301,2,1,24, 'Bulls, regular runs', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (302,2,1,24, 'Bulls, special & limited runs', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (303,2,1,24, 'Cows and Calves', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (304,2,1,24, 'Dogs', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (305,2,1,24, 'Other Realistic Animals', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (306,2,1,24, 'Fantasy, all colors', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (307,2,1,24, 'Clocks and Lamps', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (308,2,1,24, 'Horses with original plastic riders and/or tack', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (309,2,1,24, 'Horses attached to bases or produced with other accessories & Flocked models', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (310,2,1,24, 'Models with original stickers', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (311,2,1,24, 'Vintage models in or with original package/box', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (25,2,2,3, 'Unrealistic Color Section One', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (312,2,1,25, 'Wood grains - standing adults', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (313,2,1,25, 'Wood grains - action adults', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (314,2,1,25, 'Wedgewood & Copenhagen - Vintage', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (315,2,1,25, 'Wedgewood & Copenhagen - Modern', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (316,2,1,25, 'Gold Charm & Florentine - Vintage', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (317,2,1,25, 'Gold Charm & Florentine – Modern', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (318,2,1,25, 'Silver & Silver Filigree', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (26,2,2,3, 'Unrealistic Color Section Two', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (319,2,1,26, 'Models with an unrealistic design', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (320,2,1,26, 'Chalkies & Pearlies - standing adults', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (321,2,1,26, 'Chalkies & Pearlies - action adults', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (322,2,1,26, 'Charcoals & Smoke', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (323,2,1,26, 'Red Roan', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (324,2,1,26, 'Other Unrealistic Color Equine', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (325,2,1,26, 'Unrealistic Color Non-Equine', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (27,2,2,3, 'Limited Run Section One', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (326,2,1,27, 'Unrealistic Color or Fantasy', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (327,2,1,27, 'Light Breeds', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (328,2,1,27, 'Gaited Breeds', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (329,2,1,27, 'Stock Breeds', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (330,2,1,27, 'Spanish Breeds', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (331,2,1,27, 'TB/Racing Breeds', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (332,2,1,27, 'WB/Carriage Breeds', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (333,2,1,27, 'Draft Breeds & Pony Breeds', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (334,2,1,27, 'Other Breeds & Mixed Breeds', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (28,2,2,3, 'Limited Run Section Two', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (335,2,1,28, 'Connoisseur Light/Gaited Breeds', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (336,2,1,28, 'Connoisseur Stock/Spanish Breeds', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (337,2,1,28, 'Connoisseur TB/WB/Racing/Carriage Breeds', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (338,2,1,28, 'Connoisseur Draft/Pony/Other/Mixed/Unrealistic', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (339,2,1,28, 'OOAK/Test Light/Gaited Breeds', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (340,2,1,28, 'OOAK/Test Stock/Spanish Breeds', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (341,2,1,28, 'OOAK/Test TB/WB/Racing/Carriage Breeds', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (342,2,1,28, 'OOAK/Test Draft/Pony/Other/Mixed/Unrealistic', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (29,2,2,3, 'Porcelains, Factory Resins, Metals Section (ALL)', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (343,2,1,29, 'Light & Gaited Breeds', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (344,2,1,29, 'Stock & Spanish Breeds', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (345,2,1,29, 'Sport & Draft Breeds', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (346,2,1,29, 'Pony & Other/Mixed Breeds', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (4,2,3,null, 'CUSTOMIZED DIVISION', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (30,2,2,4, 'Draft Breed & Type Section', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (400,2,1,30, 'Custom Glazed Porcelains', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (401,2,1,30, 'United Kingdom & French Breeds', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (402,2,1,30, 'European, Russian, and Other Pure/Mixed Breeds', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (403,2,1,30, 'Donkeys, Mules, Zebras, Primitives & Non-Equids', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (31,2,2,4, 'Pony Breed & Type Section', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (404,2,1,31, 'United Kingdom Breeds', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (405,2,1,31, 'European, Asian, African, Australian Breeds', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (406,2,1,31, 'American Breeds', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (407,2,1,31, 'Miniature Horses, & Other Pure/Mixed', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (32,2,2,4, 'Stock Breed & Type Section', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (408,2,1,32, 'Quarter Horse', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (409,2,1,32, 'Appaloosa', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (410,2,1,32, 'Paint', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (411,2,1,32, 'North American & Color Breeds, Other Pure/Mixed', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (33,2,2,4, 'Light & Gaited Breed & Type Section', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (412,2,1,33, 'Arabian', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (413,2,1,33, 'Part-Arabian & Arabian Types', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (414,2,1,33, 'TWH, MFT, RMH, ASB', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (415,2,1,33, 'Morgan & Other Pure/Mixed', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (34,2,2,4, 'Sport Breed & Type Section', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (416,2,1,34, 'Thoroughbred', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (417,2,1,34, 'Warmbloods', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (418,2,1,34, 'Carriage & Driving Breeds', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (419,2,1,34, 'Harness Racing Breeds, Other Pure/Mixed', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (35,2,2,4, 'Spanish & Other Breed & Type Section', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (420,2,1,35, 'Andalusian, Luisitaino, Paso Fino, Per. Paso', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (421,2,1,35, 'Mustangs, all types and origins', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (422,2,1,35, 'Other Iberian Breeds and Other Pure/Mixed', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (423,2,1,35, 'All Other Pure/Rare Breeds & Mixed Breeds', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (36,2,2,4, 'Miscellaneous Section', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (424,2,1,36, 'Fantasy animal, including foals', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (425,2,1,36, 'Unrealistic Color (non-fantasy)', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (426,2,1,36, 'Dogs, Cats, Cattle, & Other Animals, all scales', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (427,2,1,36, 'Unrealistic Color or Fantasy Minis, including foals', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (37,2,2,4, 'Customized by Amateur Owner Section - all scales', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (428,2,1,37, 'Draft Breeds/Types', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (429,2,1,37, 'Pony Breeds /Types', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (430,2,1,37, 'Stock, Spanish & Other Breeds/Types', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (431,2,1,37, 'Light & Gaited Breeds/Types', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (432,2,1,37, 'Sport & Carriage Breeds/Types', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (433,2,1,37, 'Longears, Zebra, Other Types', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (434,2,1,37, 'Foals, all breeds', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (435,2,1,37, 'Fantasy/Unrealistic Color', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (5,2,3,null, 'FOAL DIVISION', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (38,2,2,5, 'Regular Run OF Section', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (501,2,1,38, 'Draft Breeds & Types', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (502,2,1,38, 'Pony Breeds & Types', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (503,2,1,38, 'Stock Breeds & Types', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (504,2,1,38, 'Light & Gaited Breeds & Types', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (505,2,1,38, 'Sport Breeds & Types', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (506,2,1,38, 'Spanish, Mustangs, & Other Breeds/Types', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (39,2,2,5, 'Special Run OF Section', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (507,2,1,39, 'Draft Breeds & Types', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (508,2,1,39, 'Pony Breeds & Types', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (509,2,1,39, 'Stock Breeds & Types', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (510,2,1,39, 'Light & Gaited Breeds & Types', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (511,2,1,39, 'Sport Breeds & Types', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (512,2,1,39, 'Spanish, Mustangs & Other Breeds/Types', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (40,2,2,5, 'Collectibility OF Section (includes SM’s)', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (513,2,1,40, 'Woodgrain, Red Roan', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (514,2,1,40, 'Wedgewood/Copenhagen, Gold Charm/Florentine', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (515,2,1,40, 'Limited Run (except OOAK’s)', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (516,2,1,40, 'Chalkies & Pearlies', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (517,2,1,40, 'Charcoal & Smoke (incl. glossy)', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (518,2,1,40, 'Other Collectible, incl. Keychains', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (41,2,2,5, 'Customized Section (includes SM’s)', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (519,2,1,41, 'Draft Breeds & Types', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (520,2,1,41, 'Pony Breeds & Types', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (521,2,1,41, 'Stock Breeds & Types', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (522,2,1,41, 'Light & Gaited Breeds & Types', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (523,2,1,41, 'Sport Breeds & Types', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (524,2,1,41, 'Spanish, Mustangs & Other Breeds/Types', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (42,2,2,5, 'O.F. Mini Section (RR & SR)', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (525,2,1,42, 'Draft Breeds & Types', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (526,2,1,42, 'Pony Breeds & Types', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (527,2,1,42, 'Stock Breeds & Types', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (528,2,1,42, 'Light & Gaited Breeds & Types', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (529,2,1,42, 'Sport Breeds & Types', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (530,2,1,42, 'Spanish, Mustangs & Other Breeds/Types', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (6,2,3,null, 'MINI DIVISION', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (43,2,2,6, 'Original Finish (RR & SR) Section One', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (601,2,1,43, 'Draft Breeds', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (602,2,1,43, 'Pony Breeds', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (603,2,1,43, 'Arabian & Part Arabian', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (604,2,1,43, 'Morgan & Gaited', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (605,2,1,43, 'Spanish & Mustangs (all)', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (606,2,1,43, 'Longears, & Other Pure & Mixed', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (44,2,2,6, 'Original Finish (RR & SR) Section Two', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (607,2,1,44, 'Quarter Horse', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (608,2,1,44, 'Appaloosa', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (609,2,1,44, 'Paint', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (610,2,1,44, 'Thoroughbred/Racing Breeds', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (611,2,1,44, 'Warmblood/Carriage Breeds', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (612,2,1,44, 'Other Pure & Mixed, & Rare Breeds', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (45,2,2,6, 'Customized Section', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (613,2,1,45, 'Draft Breeds & Types', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (614,2,1,45, 'Pony Breeds & Types', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (615,2,1,45, 'Stock Breeds & Types', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (616,2,1,45, 'Sport/Carriage Breeds & Types', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (617,2,1,45, 'Light Breeds & Types', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (618,2,1,45, 'Gaited Breeds & Types', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (619,2,1,45, 'Spanish Breeds & Types', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (620,2,1,45, 'Other Pure/Mixed & Mustangs (all)', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (46,2,2,6, 'Collectibility', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (621,2,1,46, 'Keychains', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (622,2,1,46, 'Copenhagen/Gold Charm/Florentine/Wedgewood', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (623,2,1,46, 'Unrealistic Designs', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (624,2,1,46, 'Unpainted, Metallic, Unrealistic Glossy', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (625,2,1,46, 'Other Collectible (incl. Flockies, no ornaments)', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (626,2,1,46, 'Non-Equine', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (627,2,1,46, 'Fantasy', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (47,2,2,6, 'NOVICE PERFORMANCE SECTION', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (801,2,1,47, 'Harness / Other Performance', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (802,2,1,47, 'Costume / Parade', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (803,2,1,47, 'Western Trail', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (804,2,1,47, 'Western Stock Work/Gymkhana/Other Western', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (805,2,1,47, 'Western Pleasure', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (806,2,1,47, 'Hunter Over Fences / Jumper / Cross Country', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (807,2,1,47, 'English Trail/Gymkhana/Other English', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (808,2,1,47, 'Huntseat Pleasure', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (7,2,3,null, 'OPEN O.F. PERFORMANCE DIVISION', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (48,2,2,7, 'Miscellaneous Performance Section', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (701,2,1,48, 'Harness Events', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (702,2,1,48, 'Pleasure, Fine, or Draft Harness', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (703,2,1,48, 'Park / Saddleseat', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (704,2,1,48, 'Indian Costume', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (705,2,1,48, 'Arabian Costume', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (706,2,1,48, 'Parade', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (707,2,1,48, 'Other Costume', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (708,2,1,48, 'Other Performance', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (709,2,1,48, 'Scene', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (710,2,1,48, 'Showmanship', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (49,2,2,7, 'Huntseat Performance Section', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (711,2,1,49, 'Jumper/Cross Country/Eventing', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (712,2,1,49, 'Other English, including Gymkahna', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (713,2,1,49, 'English Trail', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (714,2,1,49, 'Hunter Over Fences', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (715,2,1,49, 'Huntseat Pleasure', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (716,2,1,49, 'Dressage', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (50,2,2,7, 'Western Performance Section', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (717,2,1,50, 'Roping', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (718,2,1,50, 'Cutting & Other Stock Work', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (719,2,1,50, 'Western Games', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (720,2,1,50, 'Other Western, including Patternwork', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (721,2,1,50, 'Western Trail', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (722,2,1,50, 'Western Pleasure', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (8,2,3,null, 'OPEN CM PERFORMANCE DIVISION', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (51,2,2,8, 'Huntseat Performance Section', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (901,2,1,51, 'Jumper/Cross Country/Eventing', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (902,2,1,51, 'Other English, including Gymkahna', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (903,2,1,51, 'English Trail', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (904,2,1,51, 'Hunter Over Fences', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (905,2,1,51, 'Huntseat Pleasure', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (906,2,1,51, 'Dressage', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (52,2,2,8, 'Western Performance Section', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (907,2,1,52, 'Roping', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (908,2,1,52, 'Cutting & Other Stock Work', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (909,2,1,52, 'Western Games', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (910,2,1,52, 'Other Western, including Patternwork', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (911,2,1,52, 'Western Trail', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (912,2,1,52, 'Western Pleasure', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (53,2,2,8, 'Miscellaneous Performance Section', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (913,2,1,53, 'Harness Events', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (914,2,1,53, 'Pleasure, Fine, or Draft Harness', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (915,2,1,53, 'Park / Saddleseat', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (916,2,1,53, 'Indian Costume', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (917,2,1,53, 'Arabian Costume', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (918,2,1,53, 'Parade', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (919,2,1,53, 'Other Costume', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (920,2,1,53, 'Other Performance', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (921,2,1,53, 'Scene', NOW());
insert into horseshow.DIVISION(ID, SHOW_ID,DIVISION_TYPE_ID,PRIMARY_DIVISION_ID,NAME,ADD_DATE) values (922,2,1,53, 'Showmanship', NOW());
